/*
 * FALAJ Daily Farm Planner — Harvest Moon-inspired daily loop
 * Design: Professional, clean, adult-oriented — no cartoonish elements
 * Features: Morning plan, editable tasks, events, reminders, progress tracking
 * Inspired by: Harvest Moon daily cycle — wake up, check farm, do tasks, track progress
 */
import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useLocation } from "wouter";
import { useAppState } from "@/contexts/AppStateContext";
import BottomNav from "@/components/BottomNav";
import {
  ArrowLeft, Sun, Sunset, Moon, CheckCircle2, Circle,
  Plus, Edit3, Trash2, Clock, AlertTriangle, Calendar,
  Droplets, Leaf, TrendingUp, Truck, ChevronRight,
  Star, Zap, CloudSun, BarChart3, X, Save
} from "lucide-react";

interface FarmTask {
  id: string;
  title: string;
  description: string;
  timeSlot: "morning" | "midday" | "afternoon" | "evening";
  category: "irrigation" | "crops" | "harvest" | "maintenance" | "trading" | "admin" | "custom";
  completed: boolean;
  priority: "high" | "medium" | "low";
  xpReward: number;
  autoGenerated: boolean;
  linkedTo?: string; // sensor, crop, order ID
}

interface FarmEvent {
  id: string;
  title: string;
  time: string;
  type: "delivery" | "meeting" | "deadline" | "reminder" | "weather";
  urgent: boolean;
}

const categoryIcons: Record<string, any> = {
  irrigation: Droplets,
  crops: Leaf,
  harvest: Star,
  maintenance: Zap,
  trading: TrendingUp,
  admin: BarChart3,
  custom: Calendar,
};

const categoryColors: Record<string, string> = {
  irrigation: "text-blue-600 bg-blue-50",
  crops: "text-green-600 bg-green-50",
  harvest: "text-amber-600 bg-amber-50",
  maintenance: "text-slate-600 bg-slate-50",
  trading: "text-teal-600 bg-teal-50",
  admin: "text-indigo-600 bg-indigo-50",
  custom: "text-gray-600 bg-gray-50",
};

const priorityColors: Record<string, string> = {
  high: "bg-red-100 text-red-700",
  medium: "bg-amber-100 text-amber-700",
  low: "bg-slate-100 text-slate-600",
};

const timeSlotInfo = {
  morning: { label: "Morning", time: "6:00 - 10:00 AM", icon: Sun, color: "text-amber-600" },
  midday: { label: "Midday", time: "10:00 AM - 2:00 PM", icon: Sun, color: "text-orange-600" },
  afternoon: { label: "Afternoon", time: "2:00 - 6:00 PM", icon: Sunset, color: "text-rose-600" },
  evening: { label: "Evening", time: "6:00 - 9:00 PM", icon: Moon, color: "text-indigo-600" },
};

export default function DailyPlanner() {
  const [, setLocation] = useLocation();
  const { user, sensors, crops, orders, valves, addXP, addNotification } = useAppState();

  // Generate today's tasks based on real farm data
  const [tasks, setTasks] = useState<FarmTask[]>(() => {
    const generated: FarmTask[] = [];

    // Morning irrigation tasks from valve schedules
    valves.filter(v => v.auto).forEach((v, i) => {
      generated.push({
        id: `auto-irr-${i}`,
        title: `Irrigation cycle — ${v.zone}`,
        description: v.status === "open" ? `Currently running at ${v.flowRate} L/min` : `Scheduled: ${v.schedule}`,
        timeSlot: "morning",
        category: "irrigation",
        completed: v.status === "open",
        priority: "high",
        xpReward: 20,
        autoGenerated: true,
        linkedTo: v.id,
      });
    });

    // Sensor check tasks from alerts
    const alertSensors = sensors.filter(s => s.status === "alert" || s.status === "critical");
    if (alertSensors.length > 0) {
      generated.push({
        id: "auto-sensor-check",
        title: `Review ${alertSensors.length} sensor alert${alertSensors.length > 1 ? "s" : ""}`,
        description: alertSensors.map(s => `${s.name} in ${s.zone}: Moisture ${s.moisture}%, Temp ${s.temperature}°C, pH ${s.ph}`).join("; "),
        timeSlot: "morning",
        category: "maintenance",
        completed: false,
        priority: "high",
        xpReward: 30,
        autoGenerated: true,
      });
    }

    // Crop care tasks
    crops.filter(c => c.health < 90).forEach((c, i) => {
      generated.push({
        id: `auto-crop-${i}`,
        title: `Check ${c.name} health — ${c.zone}`,
        description: `Health: ${c.health}%, Stage: ${c.stage}, Progress: ${c.progress}%`,
        timeSlot: "morning",
        category: "crops",
        completed: false,
        priority: c.health < 80 ? "high" : "medium",
        xpReward: 25,
        autoGenerated: true,
        linkedTo: c.id,
      });
    });

    // Fertilizer application
    const needsFertilizer = crops.filter(c => c.fertilizerNeeded > 0.5);
    if (needsFertilizer.length > 0) {
      generated.push({
        id: "auto-fertilizer",
        title: `Apply fertilizer — ${needsFertilizer.length} zone${needsFertilizer.length > 1 ? "s" : ""}`,
        description: needsFertilizer.map(c => `${c.name}: ${c.fertilizerNeeded} kg`).join(", "),
        timeSlot: "morning",
        category: "crops",
        completed: false,
        priority: "medium",
        xpReward: 35,
        autoGenerated: true,
      });
    }

    // Harvest tasks for mature crops
    crops.filter(c => c.progress >= 85).forEach((c, i) => {
      generated.push({
        id: `auto-harvest-${i}`,
        title: `Harvest ${c.name}`,
        description: `${c.progress}% mature — ready for harvest in ${c.zone}`,
        timeSlot: "midday",
        category: "harvest",
        completed: false,
        priority: "high",
        xpReward: 50,
        autoGenerated: true,
        linkedTo: c.id,
      });
    });

    // Order fulfillment tasks
    orders.filter(o => o.status === "confirmed" || o.status === "pending").forEach((o, i) => {
      generated.push({
        id: `auto-order-${i}`,
        title: `${o.status === "pending" ? "Confirm" : "Prepare"} order — ${o.buyer}`,
        description: `${o.product} · ${o.quantity} · ${o.total}`,
        timeSlot: "midday",
        category: "trading",
        completed: false,
        priority: o.status === "pending" ? "high" : "medium",
        xpReward: 40,
        autoGenerated: true,
        linkedTo: o.id,
      });
    });

    // Afternoon irrigation
    generated.push({
      id: "auto-pm-irrigation",
      title: "Evening irrigation cycle",
      description: "Automated evening watering for Zones B and D",
      timeSlot: "afternoon",
      category: "irrigation",
      completed: false,
      priority: "medium",
      xpReward: 20,
      autoGenerated: true,
    });

    // Financial review
    generated.push({
      id: "auto-finance",
      title: "Review daily financial summary",
      description: "Check revenue, expenses, and pending invoices",
      timeSlot: "afternoon",
      category: "admin",
      completed: false,
      priority: "low",
      xpReward: 15,
      autoGenerated: true,
    });

    // Marketplace check
    generated.push({
      id: "auto-marketplace",
      title: "Check marketplace for new buyer requests",
      description: "Review new B2B demand and marketplace orders",
      timeSlot: "midday",
      category: "trading",
      completed: false,
      priority: "medium",
      xpReward: 20,
      autoGenerated: true,
    });

    // Evening planning
    generated.push({
      id: "auto-plan-tomorrow",
      title: "Review tomorrow's forecast and plan",
      description: "Check weather, upcoming deliveries, and sensor trends",
      timeSlot: "evening",
      category: "admin",
      completed: false,
      priority: "low",
      xpReward: 15,
      autoGenerated: true,
    });

    return generated;
  });

  const [events] = useState<FarmEvent[]>([
    { id: "e1", title: "Jumeirah Group delivery deadline", time: "Friday, March 13", type: "deadline", urgent: true },
    { id: "e2", title: "Etihad Catering — respond to demand", time: "Today by 5:00 PM", type: "deadline", urgent: true },
    { id: "e3", title: "Fertilizer stock reorder", time: "By Wednesday", type: "reminder", urgent: false },
    { id: "e4", title: "Possible sandstorm", time: "Thursday", type: "weather", urgent: true },
    { id: "e5", title: "Monthly farm inspection", time: "March 15", type: "meeting", urgent: false },
  ]);

  const [showAddTask, setShowAddTask] = useState(false);
  const [editingTask, setEditingTask] = useState<string | null>(null);
  const [newTask, setNewTask] = useState({ title: "", description: "", timeSlot: "morning" as const, category: "custom" as const, priority: "medium" as const });

  const completedCount = tasks.filter(t => t.completed).length;
  const totalXP = tasks.filter(t => t.completed).reduce((sum, t) => sum + t.xpReward, 0);
  const progressPercent = Math.round((completedCount / tasks.length) * 100);

  const tasksBySlot = useMemo(() => {
    const grouped: Record<string, FarmTask[]> = { morning: [], midday: [], afternoon: [], evening: [] };
    tasks.forEach(t => grouped[t.timeSlot].push(t));
    return grouped;
  }, [tasks]);

  const toggleTask = (id: string) => {
    setTasks(prev => prev.map(t => {
      if (t.id === id) {
        const nowCompleted = !t.completed;
        if (nowCompleted) {
          addXP(t.xpReward);
          addNotification({
            id: `n-${Date.now()}`,
            title: "Task Completed",
            message: `${t.title} — +${t.xpReward} XP`,
            type: "reward",
            read: false,
            time: "Just now",
          });
        }
        return { ...t, completed: nowCompleted };
      }
      return t;
    }));
  };

  const deleteTask = (id: string) => {
    setTasks(prev => prev.filter(t => t.id !== id));
  };

  const addTask = () => {
    if (!newTask.title.trim()) return;
    const task: FarmTask = {
      id: `custom-${Date.now()}`,
      title: newTask.title,
      description: newTask.description,
      timeSlot: newTask.timeSlot,
      category: newTask.category,
      completed: false,
      priority: newTask.priority,
      xpReward: (newTask.priority as string) === "high" ? 40 : (newTask.priority as string) === "medium" ? 25 : 15,
      autoGenerated: false,
    };
    setTasks(prev => [...prev, task]);
    setNewTask({ title: "", description: "", timeSlot: "morning", category: "custom", priority: "medium" });
    setShowAddTask(false);
  };

  const now = new Date();
  const hour = now.getHours();
  const currentSlot = hour < 10 ? "morning" : hour < 14 ? "midday" : hour < 18 ? "afternoon" : "evening";
  const greeting = hour < 12 ? "Good Morning" : hour < 17 ? "Good Afternoon" : "Good Evening";

  return (
    <div className="min-h-screen bg-background pb-24">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-gradient-to-br from-emerald-700 to-teal-800 text-white shadow-lg">
        <div className="max-w-[480px] mx-auto px-4 pt-4 pb-5">
          <div className="flex items-center gap-3 mb-4">
            <button onClick={() => setLocation("/dashboard")} className="p-2 -ml-2 rounded-xl hover:bg-white/10 transition-colors">
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div className="flex-1">
              <p className="text-emerald-200 text-xs font-medium">{now.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}</p>
              <h1 className="text-lg font-bold">{greeting}, {user.name.split(" ")[0]}</h1>
            </div>
            <button
              onClick={() => setLocation("/ai-assistant")}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-white/15 rounded-lg text-xs font-medium hover:bg-white/25 transition-colors"
            >
              Ask Obaid
            </button>
          </div>

          {/* Day Progress */}
          <div className="bg-white/10 backdrop-blur-sm rounded-xl p-3">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium">Today's Progress</span>
              <span className="text-sm font-bold">{completedCount}/{tasks.length} tasks</span>
            </div>
            <div className="w-full h-2 bg-white/20 rounded-full overflow-hidden">
              <motion.div
                className="h-full bg-white rounded-full"
                initial={{ width: 0 }}
                animate={{ width: `${progressPercent}%` }}
                transition={{ duration: 0.8, ease: "easeOut" }}
              />
            </div>
            <div className="flex items-center justify-between mt-2">
              <span className="text-xs text-emerald-200">{progressPercent}% complete</span>
              <span className="text-xs text-emerald-200 font-medium">+{totalXP} XP earned today</span>
            </div>
          </div>
        </div>
      </header>

      <div className="max-w-[480px] mx-auto px-4 py-4">
        {/* Urgent Events */}
        {events.filter(e => e.urgent).length > 0 && (
          <div className="mb-5">
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <AlertTriangle className="w-3.5 h-3.5 text-red-500" />
              Requires Attention
            </h3>
            <div className="space-y-2">
              {events.filter(e => e.urgent).map(event => (
                <div key={event.id} className="flex items-center gap-3 p-3 bg-red-50 border border-red-100 rounded-xl">
                  <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${
                    event.type === "weather" ? "bg-amber-100" : event.type === "deadline" ? "bg-red-100" : "bg-blue-100"
                  }`}>
                    {event.type === "weather" ? <CloudSun className="w-4 h-4 text-amber-600" /> :
                     event.type === "deadline" ? <Clock className="w-4 h-4 text-red-600" /> :
                     <Truck className="w-4 h-4 text-blue-600" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-foreground truncate">{event.title}</p>
                    <p className="text-[11px] text-muted-foreground">{event.time}</p>
                  </div>
                  <ChevronRight className="w-4 h-4 text-muted-foreground shrink-0" />
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Time Slots */}
        {(["morning", "midday", "afternoon", "evening"] as const).map(slot => {
          const info = timeSlotInfo[slot];
          const Icon = info.icon;
          const slotTasks = tasksBySlot[slot];
          const isCurrentSlot = slot === currentSlot;

          if (slotTasks.length === 0) return null;

          return (
            <div key={slot} className="mb-5">
              <div className="flex items-center gap-2 mb-2.5">
                <Icon className={`w-4 h-4 ${info.color}`} />
                <h3 className="text-sm font-bold text-foreground">{info.label}</h3>
                <span className="text-[11px] text-muted-foreground">{info.time}</span>
                {isCurrentSlot && (
                  <span className="text-[10px] font-semibold bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full ml-auto">
                    NOW
                  </span>
                )}
              </div>

              <div className="space-y-2">
                {slotTasks.map(task => {
                  const CatIcon = categoryIcons[task.category] || Calendar;
                  const isEditing = editingTask === task.id;

                  return (
                    <motion.div
                      key={task.id}
                      layout
                      className={`flex items-start gap-3 p-3 rounded-xl border transition-all ${
                        task.completed
                          ? "bg-emerald-50/50 border-emerald-100 opacity-70"
                          : isCurrentSlot
                          ? "bg-white border-emerald-200 shadow-sm"
                          : "bg-white border-border/50"
                      }`}
                    >
                      <button
                        onClick={() => toggleTask(task.id)}
                        className="mt-0.5 shrink-0"
                      >
                        {task.completed ? (
                          <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                        ) : (
                          <Circle className="w-5 h-5 text-muted-foreground/40 hover:text-emerald-400 transition-colors" />
                        )}
                      </button>

                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-0.5">
                          <div className={`w-5 h-5 rounded flex items-center justify-center shrink-0 ${categoryColors[task.category]}`}>
                            <CatIcon className="w-3 h-3" />
                          </div>
                          <p className={`text-sm font-medium truncate ${task.completed ? "line-through text-muted-foreground" : "text-foreground"}`}>
                            {task.title}
                          </p>
                        </div>
                        <p className="text-[11px] text-muted-foreground mt-0.5 line-clamp-1">{task.description}</p>
                        <div className="flex items-center gap-2 mt-1.5">
                          <span className={`text-[10px] font-medium px-1.5 py-0.5 rounded ${priorityColors[task.priority]}`}>
                            {task.priority}
                          </span>
                          <span className="text-[10px] text-emerald-600 font-medium">+{task.xpReward} XP</span>
                          {task.autoGenerated && (
                            <span className="text-[10px] text-muted-foreground">Auto-generated</span>
                          )}
                        </div>
                      </div>

                      {!task.autoGenerated && (
                        <button
                          onClick={() => deleteTask(task.id)}
                          className="p-1.5 rounded-lg hover:bg-red-50 text-muted-foreground hover:text-red-500 transition-colors shrink-0"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </motion.div>
                  );
                })}
              </div>
            </div>
          );
        })}

        {/* Upcoming Events */}
        <div className="mb-5">
          <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
            <Calendar className="w-3.5 h-3.5" />
            Upcoming Events
          </h3>
          <div className="space-y-2">
            {events.filter(e => !e.urgent).map(event => (
              <div key={event.id} className="flex items-center gap-3 p-3 bg-white border border-border/50 rounded-xl">
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${
                  event.type === "meeting" ? "bg-blue-50" : event.type === "reminder" ? "bg-amber-50" : "bg-slate-50"
                }`}>
                  {event.type === "meeting" ? <Calendar className="w-4 h-4 text-blue-600" /> :
                   <Clock className="w-4 h-4 text-amber-600" />}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-foreground">{event.title}</p>
                  <p className="text-[11px] text-muted-foreground">{event.time}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Add Task Button */}
        <button
          onClick={() => setShowAddTask(true)}
          className="w-full flex items-center justify-center gap-2 p-3 border-2 border-dashed border-emerald-200 rounded-xl text-emerald-700 font-medium text-sm hover:bg-emerald-50 transition-colors active:scale-[0.98]"
        >
          <Plus className="w-4 h-4" />
          Add Custom Task
        </button>
      </div>

      {/* Add Task Modal */}
      <AnimatePresence>
        {showAddTask && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-end justify-center"
            onClick={() => setShowAddTask(false)}
          >
            <motion.div
              initial={{ y: "100%" }}
              animate={{ y: 0 }}
              exit={{ y: "100%" }}
              transition={{ type: "spring", damping: 25, stiffness: 300 }}
              className="w-full max-w-[480px] bg-white rounded-t-2xl p-5"
              onClick={e => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-bold">Add Task</h3>
                <button onClick={() => setShowAddTask(false)} className="p-2 rounded-xl hover:bg-muted transition-colors">
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="space-y-3">
                <div>
                  <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Task Name</label>
                  <input
                    type="text"
                    value={newTask.title}
                    onChange={e => setNewTask(prev => ({ ...prev, title: e.target.value }))}
                    placeholder="e.g., Inspect greenhouse ventilation"
                    className="w-full mt-1 px-3 py-2.5 border border-border rounded-xl text-sm outline-none focus:border-emerald-300 focus:ring-2 focus:ring-emerald-100"
                  />
                </div>

                <div>
                  <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Description</label>
                  <input
                    type="text"
                    value={newTask.description}
                    onChange={e => setNewTask(prev => ({ ...prev, description: e.target.value }))}
                    placeholder="Optional details"
                    className="w-full mt-1 px-3 py-2.5 border border-border rounded-xl text-sm outline-none focus:border-emerald-300 focus:ring-2 focus:ring-emerald-100"
                  />
                </div>

                <div className="grid grid-cols-3 gap-2">
                  <div>
                    <label className="text-[10px] font-semibold text-muted-foreground uppercase">Time</label>
                    <select
                      value={newTask.timeSlot}
                      onChange={e => setNewTask(prev => ({ ...prev, timeSlot: e.target.value as any }))}
                      className="w-full mt-1 px-2 py-2 border border-border rounded-lg text-xs outline-none focus:border-emerald-300"
                    >
                      <option value="morning">Morning</option>
                      <option value="midday">Midday</option>
                      <option value="afternoon">Afternoon</option>
                      <option value="evening">Evening</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-[10px] font-semibold text-muted-foreground uppercase">Category</label>
                    <select
                      value={newTask.category}
                      onChange={e => setNewTask(prev => ({ ...prev, category: e.target.value as any }))}
                      className="w-full mt-1 px-2 py-2 border border-border rounded-lg text-xs outline-none focus:border-emerald-300"
                    >
                      <option value="irrigation">Irrigation</option>
                      <option value="crops">Crops</option>
                      <option value="harvest">Harvest</option>
                      <option value="maintenance">Maintenance</option>
                      <option value="trading">Trading</option>
                      <option value="admin">Admin</option>
                      <option value="custom">Other</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-[10px] font-semibold text-muted-foreground uppercase">Priority</label>
                    <select
                      value={newTask.priority}
                      onChange={e => setNewTask(prev => ({ ...prev, priority: e.target.value as any }))}
                      className="w-full mt-1 px-2 py-2 border border-border rounded-lg text-xs outline-none focus:border-emerald-300"
                    >
                      <option value="high">High</option>
                      <option value="medium">Medium</option>
                      <option value="low">Low</option>
                    </select>
                  </div>
                </div>

                <button
                  onClick={addTask}
                  disabled={!newTask.title.trim()}
                  className="w-full py-3 bg-emerald-700 text-white font-semibold rounded-xl disabled:opacity-40 hover:bg-emerald-800 transition-all active:scale-[0.98]"
                >
                  Add Task
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <BottomNav />
    </div>
  );
}
