/**
 * Navigation registry. Labels are i18n keys (messages/<locale>/nav.json). Feature owners
 * do not edit this file; routes were reserved up front.
 */
export type NavItem = { key: string; href: string; icon: string; match?: string[] };

export const PUBLIC_NAV: NavItem[] = [
  { key: "nav.home", href: "/", icon: "Home" },
  { key: "nav.programs", href: "/programs", icon: "Route" },
  { key: "nav.courses", href: "/courses", icon: "BookOpen" },
  { key: "nav.enterprise", href: "/enterprise", icon: "Building2" },
  { key: "nav.about", href: "/about", icon: "Info" },
];

export const LEARNER_NAV: NavItem[] = [
  { key: "nav.home", href: "/home", icon: "Home" },
  { key: "nav.learn", href: "/learn", icon: "GraduationCap", match: ["/learn", "/paths"] },
  { key: "nav.explore", href: "/explore", icon: "Compass", match: ["/explore", "/courses"] },
  { key: "nav.projects", href: "/projects", icon: "FolderKanban" },
  { key: "nav.skills", href: "/skills", icon: "Radar" },
  { key: "nav.aiTutor", href: "/ai", icon: "Sparkles" },
  { key: "nav.analytics", href: "/analytics", icon: "ChartNoAxesCombined" },
  { key: "nav.certificates", href: "/certificates", icon: "Award" },
  { key: "nav.profile", href: "/profile", icon: "UserRound" },
];

/** Shown on mobile bottom bar (max 5). */
export const MOBILE_NAV_KEYS = ["nav.home", "nav.learn", "nav.explore", "nav.aiTutor", "nav.profile"];

export const INSTRUCTOR_NAV: NavItem[] = [
  { key: "nav.instructorDashboard", href: "/instructor", icon: "LayoutDashboard" },
  { key: "nav.instructorCourses", href: "/instructor/courses", icon: "BookOpen" },
  { key: "nav.instructorStudents", href: "/instructor/students", icon: "Users" },
  { key: "nav.instructorReviews", href: "/instructor/reviews", icon: "ClipboardCheck" },
  { key: "nav.instructorQuestions", href: "/instructor/questions", icon: "MessageCircleQuestion" },
];

export const ORG_NAV: NavItem[] = [
  { key: "nav.orgOverview", href: "/org", icon: "Building2" },
  { key: "nav.orgPeople", href: "/org/people", icon: "Users" },
  { key: "nav.orgPrograms", href: "/org/programs", icon: "Route" },
  { key: "nav.orgSkillsGap", href: "/org/skills-gap", icon: "Radar" },
  { key: "nav.orgAnalytics", href: "/org/analytics", icon: "ChartNoAxesCombined" },
];

export const ADMIN_NAV: NavItem[] = [
  { key: "nav.adminOverview", href: "/admin", icon: "LayoutDashboard" },
  { key: "nav.adminUsers", href: "/admin/users", icon: "Users" },
  { key: "nav.adminCourses", href: "/admin/courses", icon: "BookOpen" },
  { key: "nav.adminPaths", href: "/admin/paths", icon: "Route" },
  { key: "nav.adminInstructors", href: "/admin/instructors", icon: "UserCog" },
  { key: "nav.adminProjects", href: "/admin/projects", icon: "FolderKanban" },
  { key: "nav.adminAssessments", href: "/admin/assessments", icon: "ClipboardList" },
  { key: "nav.adminCertificates", href: "/admin/certificates", icon: "Award" },
  { key: "nav.adminCategories", href: "/admin/categories", icon: "Tags" },
  { key: "nav.adminAi", href: "/admin/ai", icon: "Sparkles" },
  { key: "nav.adminAnnouncements", href: "/admin/announcements", icon: "Megaphone" },
  { key: "nav.adminAnalytics", href: "/admin/analytics", icon: "ChartNoAxesCombined" },
  { key: "nav.adminOrganizations", href: "/admin/organizations", icon: "Building2" },
  { key: "nav.adminAudit", href: "/admin/audit", icon: "ScrollText" },
];
