import { type SeedCourse, text, video, check, activity, diagram, mc, tf, sa } from "./types";

const V = "https://www.youtube.com/embed/aircAruvnKk"; // placeholder public lecture video

export const aiFundamentals: SeedCourse = {
  slug: "ai-fundamentals",
  titleEn: "AI Fundamentals", titleAr: "أساسيات الذكاء الاصطناعي",
  summaryEn: "What AI is, what it is not, and how it already shapes work in the UAE and beyond.",
  summaryAr: "ما الذكاء الاصطناعي وما ليس كذلك، وكيف يشكّل العمل اليوم في الإمارات والعالم.",
  descriptionEn: "A jargon-free foundation. You will learn the main families of AI, how a machine \"learns\" from data, where AI creates value, and how to judge an AI claim critically. The course ends with you mapping one real process in your organisation to an AI opportunity.",
  descriptionAr: "أساس خالٍ من التعقيد. ستتعرّف على العائلات الرئيسية للذكاء الاصطناعي، وكيف «تتعلّم» الآلة من البيانات، وأين يخلق الذكاء الاصطناعي القيمة، وكيف تقيّم أي ادعاء عنه بعين ناقدة. تختتم الدورة بتحديد فرصة حقيقية للذكاء الاصطناعي في عملية من عمليات مؤسستك.",
  category: "ai", instructor: "amal.alkaabi@nokhba.demo", difficulty: "BEGINNER", hours: 8, cover: "cover-aurora", featured: true,
  outcomesEn: ["Explain the difference between rule-based systems, machine learning and generative AI", "Describe how models learn from data and why data quality matters", "Identify AI opportunities and risks in a real workflow", "Evaluate AI claims with a simple critical checklist"],
  outcomesAr: ["التمييز بين الأنظمة القائمة على القواعد وتعلّم الآلة والذكاء التوليدي", "وصف كيف تتعلّم النماذج من البيانات ولماذا تهم جودتها", "تحديد فرص ومخاطر الذكاء الاصطناعي في سير عمل حقيقي", "تقييم ادعاءات الذكاء الاصطناعي بقائمة تحقّق بسيطة"],
  prerequisitesEn: ["No technical background required"], prerequisitesAr: ["لا يتطلب خلفية تقنية"],
  skills: ["artificial-intelligence", "machine-learning", "responsible-ai"], rating: 4.8, ratingCount: 1240, enrollmentCount: 5820,
  modules: [
    { titleEn: "What AI really is", titleAr: "ما هو الذكاء الاصطناعي فعلاً", lessons: [
      { slug: "three-kinds-of-ai", titleEn: "Three kinds of AI", titleAr: "ثلاثة أنواع من الذكاء الاصطناعي", type: "VIDEO", minutes: 12, skills: ["artificial-intelligence"], freePreview: true, blocks: [
        video(V, "Overview lecture: rule-based systems, machine learning and generative AI.", "محاضرة تمهيدية: الأنظمة القائمة على القواعد، وتعلّم الآلة، والذكاء التوليدي."),
        text(`## Three families\n\nMost systems called "AI" belong to one of three families:\n\n1. **Rule-based systems** encode expert knowledge as explicit rules (\"if the invoice is over AED 50,000, route to a manager\"). They are predictable and auditable, but every new situation needs a new rule.\n2. **Machine learning (ML)** learns patterns from examples. Show a model thousands of past loan applications and outcomes, and it learns which features predict default. It generalises to new cases but can only be as good as its data.\n3. **Generative AI** produces new content — text, images, code — by learning the structure of enormous datasets. Large language models (LLMs) are the best-known example.\n\n## Why the distinction matters\n\nWhen a vendor says a product "uses AI", ask which family. A rule-based chatbot and an LLM assistant have completely different failure modes: the first fails loudly on unknown inputs, the second can fail *confidently* by inventing an answer.\n\n> **Key idea:** AI is not one technology. Choose the family that matches the problem, the data you have and the risk you can tolerate.`,
          `## ثلاث عائلات\n\nمعظم الأنظمة التي تُسمّى «ذكاءً اصطناعياً» تنتمي إلى إحدى ثلاث عائلات:\n\n1. **الأنظمة القائمة على القواعد** تُشفّر خبرة الخبراء في قواعد صريحة («إذا تجاوزت الفاتورة 50,000 درهم فحوّلها إلى المدير»). قابلة للتنبؤ والتدقيق، لكن كل حالة جديدة تحتاج قاعدة جديدة.\n2. **تعلّم الآلة** يتعلّم الأنماط من الأمثلة. اعرض على النموذج آلاف طلبات القروض السابقة ونتائجها فيتعلّم أي الخصائص تتنبّأ بالتعثّر. يعمّم على حالات جديدة لكنه لا يكون أفضل من بياناته.\n3. **الذكاء الاصطناعي التوليدي** ينتج محتوى جديداً — نصاً أو صوراً أو كوداً — بتعلّم بنية مجموعات بيانات ضخمة. النماذج اللغوية الكبيرة أشهر مثال عليه.\n\n## لماذا يهم التمييز\n\nحين يقول مورّد إن منتجه «يستخدم الذكاء الاصطناعي» اسأل: من أي عائلة؟ روبوت محادثة قائم على القواعد ومساعد يعمل بنموذج لغوي لهما أنماط فشل مختلفة تماماً: الأول يفشل بوضوح مع المدخلات المجهولة، والثاني قد يفشل *بثقة* عبر اختلاق إجابة.\n\n> **الفكرة الأساسية:** الذكاء الاصطناعي ليس تقنية واحدة. اختر العائلة التي تناسب المشكلة والبيانات المتاحة والمخاطر التي تحتملها.`),
        check("A system that routes invoices using explicit thresholds written by finance staff is best described as:", "نظام يوجّه الفواتير باستخدام حدود صريحة كتبها موظفو المالية يُوصف على أنه:", [["Rule-based", "قائم على القواعد", true, "The logic is hand-written rules, not learned from data.", "المنطق قواعد مكتوبة يدوياً، لا مُتعلَّم من البيانات."], ["Machine learning", "تعلّم آلة", false], ["Generative AI", "ذكاء توليدي", false]]),
      ] },
      { slug: "how-machines-learn", titleEn: "How machines learn from data", titleAr: "كيف تتعلّم الآلات من البيانات", minutes: 15, skills: ["machine-learning"], blocks: [
        text(`## Learning = finding a function\n\nA machine-learning model is a function that maps inputs (features) to an output (a prediction). Training means adjusting the function's internal numbers — its **parameters** — until its predictions on known examples are as close as possible to the true answers.\n\n### The loop\n\n1. **Collect** labelled examples (inputs with the right answer).\n2. **Split** them: most for training, some held back for testing.\n3. **Train**: the algorithm measures its error on the training set and nudges parameters to reduce it, thousands of times.\n4. **Evaluate** on the held-out test set. Good test performance is the only evidence the model will work on new data.\n\n### Three ways to learn\n\n- **Supervised**: examples come with labels (spam / not spam).\n- **Unsupervised**: no labels; the model finds structure (customer segments).\n- **Reinforcement**: the model acts, receives rewards, and improves (game playing, robot control).\n\n### Garbage in, garbage out\n\nIf the training data is biased, incomplete or stale, the model faithfully learns those flaws. A CV-screening model trained on a decade of past hires will learn the past's preferences — including the ones you no longer want.`,
          `## التعلّم = إيجاد دالة\n\nنموذج تعلّم الآلة دالة تربط المدخلات (الخصائص) بمخرج (تنبؤ). التدريب يعني ضبط الأرقام الداخلية للدالة — **المعاملات** — حتى تصبح تنبؤاتها على أمثلة معروفة أقرب ما يمكن إلى الإجابات الصحيحة.\n\n### الحلقة\n\n1. **اجمع** أمثلة موسومة (مدخلات مع الإجابة الصحيحة).\n2. **قسّمها**: معظمها للتدريب، وبعضها محجوز للاختبار.\n3. **درّب**: تقيس الخوارزمية خطأها على بيانات التدريب وتعدّل المعاملات لتقليله آلاف المرات.\n4. **قيّم** على بيانات الاختبار المحجوزة. الأداء الجيد على الاختبار هو الدليل الوحيد على أن النموذج سيعمل على بيانات جديدة.\n\n### ثلاث طرق للتعلّم\n\n- **الإشرافي**: الأمثلة تأتي مع وسوم (رسالة مزعجة / غير مزعجة).\n- **غير الإشرافي**: بلا وسوم؛ يكتشف النموذج البنية (شرائح العملاء).\n- **التعزيزي**: يتصرّف النموذج ويتلقّى مكافآت ويتحسّن (الألعاب، التحكم بالروبوتات).\n\n### ما يدخل رديئاً يخرج رديئاً\n\nإذا كانت بيانات التدريب متحيّزة أو ناقصة أو قديمة تعلّم النموذج هذه العيوب بأمانة. نموذج فرز السير الذاتية المدرّب على عقد من التوظيف السابق سيتعلّم تفضيلات الماضي — بما فيها ما لم تعد تريده.`),
        diagram("flowchart LR\n  A[Collect labelled data] --> B[Split train / test]\n  B --> C[Train: reduce error]\n  C --> D[Evaluate on test set]\n  D -->|good| E[Deploy & monitor]\n  D -->|poor| A", "The supervised learning loop.", "حلقة التعلّم الإشرافي."),
        check("Why is a separate test set essential?", "لماذا تُعدّ مجموعة الاختبار المنفصلة ضرورية؟", [["It makes training faster", "تجعل التدريب أسرع", false], ["It shows how the model performs on data it has not seen", "تُظهر أداء النموذج على بيانات لم يرها", true, "Performance on unseen data is the only evidence of generalisation.", "الأداء على بيانات غير مرئية هو الدليل الوحيد على التعميم."], ["It removes bias from the data", "تزيل التحيّز من البيانات", false]]),
      ] },
      { slug: "generative-ai-in-plain-words", titleEn: "Generative AI in plain words", titleAr: "الذكاء التوليدي بكلمات بسيطة", minutes: 12, skills: ["generative-ai", "llms"], blocks: [
        text(`## Predicting the next token\n\nA large language model is trained on a vast amount of text to do one thing extremely well: predict the next word (token) given everything before it. Do that billions of times with billions of parameters and something remarkable happens — the model absorbs grammar, facts, reasoning patterns and styles.\n\n## What this explains\n\n- **Fluency**: the model always produces plausible text because that is exactly what it optimises.\n- **Hallucination**: plausible is not the same as true. When the model lacks knowledge it still predicts a likely-sounding continuation.\n- **Prompt sensitivity**: everything before the answer shapes the prediction, so instructions, examples and context change results dramatically.\n\n## Grounding\n\nTo make an LLM reliable for real work, we *ground* it: give it the relevant documents in the prompt (retrieval-augmented generation), constrain it to cite sources, and keep a human in the loop for consequential decisions. This is exactly how the Nokhba AI tutor works — it reads the lesson before it answers you.`,
          `## التنبؤ بالرمز التالي\n\nيُدرَّب النموذج اللغوي الكبير على كمّ هائل من النصوص ليتقن شيئاً واحداً: التنبؤ بالكلمة (الرمز) التالية بالنظر إلى كل ما سبقها. افعل ذلك مليارات المرات بمليارات المعاملات فيحدث أمر لافت — يمتصّ النموذج القواعد والحقائق وأنماط الاستدلال والأساليب.\n\n## ما يفسّره ذلك\n\n- **الطلاقة**: ينتج النموذج دائماً نصاً معقولاً لأن هذا بالضبط ما يُحسِّنه.\n- **الهلوسة**: المعقول ليس هو الصحيح. حين تنقص النموذج المعرفة يتنبّأ مع ذلك بتكملة تبدو منطقية.\n- **الحساسية للأوامر**: كل ما قبل الإجابة يشكّل التنبؤ، لذا تغيّر التعليمات والأمثلة والسياق النتائج بشكل كبير.\n\n## التأريض\n\nلجعل النموذج موثوقاً في العمل الحقيقي «نؤرّضه»: نعطيه المستندات المناسبة في الأمر (التوليد المعزّز بالاسترجاع)، ونلزمه بذكر المصادر، ونُبقي الإنسان في الحلقة للقرارات المهمة. هكذا يعمل مرشد نخبة الذكي بالضبط — يقرأ الدرس قبل أن يجيبك.`),
        check("An LLM produced a confident but false citation. The most accurate explanation is:", "أنتج نموذج لغوي اقتباساً واثقاً لكنه خاطئ. التفسير الأدق هو:", [["It was trained on false data", "دُرّب على بيانات خاطئة", false], ["It predicted a plausible continuation without knowledge of the real source", "تنبّأ بتكملة معقولة دون معرفة بالمصدر الحقيقي", true, "Hallucination follows directly from next-token prediction.", "الهلوسة نتيجة مباشرة للتنبؤ بالرمز التالي."], ["Someone hacked the model", "اخترق أحدهم النموذج", false]]),
      ] },
    ] },
    { titleEn: "AI at work", titleAr: "الذكاء الاصطناعي في العمل", lessons: [
      { slug: "where-ai-creates-value", titleEn: "Where AI creates value", titleAr: "أين يخلق الذكاء الاصطناعي القيمة", minutes: 14, skills: ["artificial-intelligence", "digital-transformation"], blocks: [
        text(`## Four value patterns\n\n| Pattern | Example | Typical family |\n|---|---|---|\n| **Automate** a repetitive judgement | Classify incoming service requests | ML |\n| **Predict** to act earlier | Forecast water demand per district | ML |\n| **Generate** first drafts | Draft a policy summary in Arabic and English | Generative |\n| **Personalise** at scale | Recommend the next training module | ML + Generative |\n\n## A UAE lens\n\nNational strategies (the UAE AI Strategy 2031, smart-city programmes) push government entities to move from pilots to production. The entities that succeed share three habits: they start from a measurable process metric, they own their data, and they keep humans accountable for decisions.\n\n## Spotting an opportunity\n\nAsk of any process: Is it **frequent**? Is there a **clear outcome** to learn from? Is the **data captured** already? Is the **cost of a mistake** recoverable? Four yeses — a strong candidate. Two or fewer — fix the process first.`,
          `## أربعة أنماط للقيمة\n\n| النمط | مثال | العائلة المعتادة |\n|---|---|---|\n| **أتمتة** حكم متكرر | تصنيف طلبات الخدمة الواردة | تعلّم آلة |\n| **التنبؤ** للتصرف مبكراً | توقّع الطلب على المياه لكل منطقة | تعلّم آلة |\n| **توليد** المسودّات الأولى | صياغة ملخّص سياسة بالعربية والإنجليزية | توليدي |\n| **التخصيص** على نطاق واسع | اقتراح وحدة التدريب التالية | تعلّم آلة + توليدي |\n\n## عدسة إماراتية\n\nتدفع الاستراتيجيات الوطنية (استراتيجية الإمارات للذكاء الاصطناعي 2031، برامج المدن الذكية) الجهات الحكومية للانتقال من التجارب إلى الإنتاج. الجهات الناجحة تشترك في ثلاث عادات: تبدأ من مؤشر عملية قابل للقياس، وتمتلك بياناتها، وتُبقي البشر مسؤولين عن القرارات.\n\n## اكتشاف الفرصة\n\naسأل عن أي عملية: هل هي **متكررة**؟ هل لها **نتيجة واضحة** يمكن التعلّم منها؟ هل **البيانات مُلتقطة** أصلاً؟ هل **كلفة الخطأ** قابلة للتدارك؟ أربع إجابات بنعم — مرشّح قوي. اثنتان أو أقل — أصلح العملية أولاً.`),
        activity("Pick one process from your own work. Answer the four opportunity questions in writing, then decide: candidate or not?", "اختر عملية واحدة من عملك. أجب كتابةً عن أسئلة الفرصة الأربعة ثم قرر: مرشّحة أم لا؟", 15),
      ] },
      { slug: "risks-and-critical-checklist", titleEn: "Risks and a critical checklist", titleAr: "المخاطر وقائمة تحقّق ناقدة", minutes: 13, skills: ["responsible-ai"], blocks: [
        text(`## The five questions\n\nBefore trusting any AI system — a vendor demo, a research claim, an internal pilot — ask:\n\n1. **What data was it trained on, and does it resemble ours?** A fraud model trained on European card transactions may misfire on Gulf spending patterns.\n2. **How was it evaluated?** Accuracy alone hides everything. Ask for precision/recall per group and for performance on the hardest cases.\n3. **What happens when it is wrong?** Who notices, how fast, and who fixes it?\n4. **Can we explain a decision to the person affected?** Regulation increasingly requires this.\n5. **Who is accountable?** A model cannot be; a named person or team must be.\n\n## Common failure modes\n\n- **Distribution shift**: the world changes, the model does not.\n- **Automation bias**: people stop checking a system that is usually right.\n- **Feedback loops**: the model's decisions shape the data it will learn from next.\n\nThe checklist is short on purpose. Use it every time.`,
          `## الأسئلة الخمسة\n\nقبل الوثوق بأي نظام ذكاء اصطناعي — عرض مورّد، ادعاء بحثي، تجربة داخلية — اسأل:\n\n1. **على أي بيانات دُرّب، وهل تشبه بياناتنا؟** نموذج احتيال مدرّب على معاملات بطاقات أوروبية قد يخطئ مع أنماط الإنفاق الخليجية.\n2. **كيف قُيّم؟** الدقة وحدها تُخفي كل شيء. اطلب الدقة والاستدعاء لكل فئة والأداء على أصعب الحالات.\n3. **ماذا يحدث حين يخطئ؟** من يلاحظ، وبأي سرعة، ومن يصلح؟\n4. **هل نستطيع شرح القرار للشخص المتأثر؟** التشريعات تتطلب ذلك بشكل متزايد.\n5. **من المسؤول؟** لا يمكن للنموذج أن يكون؛ يجب أن يكون شخص أو فريق محدد.\n\n## أنماط الفشل الشائعة\n\n- **تحوّل التوزيع**: يتغيّر العالم ولا يتغيّر النموذج.\n- **تحيّز الأتمتة**: يتوقف الناس عن التحقق من نظام غالباً ما يكون محقاً.\n- **حلقات التغذية الراجعة**: قرارات النموذج تشكّل البيانات التي سيتعلّم منها لاحقاً.\n\nالقائمة قصيرة عمداً. استخدمها كل مرة.`),
        check("A model's accuracy is 97%. What should you ask next?", "دقة النموذج 97%. ما الذي تسأل عنه بعد ذلك؟", [["Nothing — 97% is excellent", "لا شيء — 97% ممتازة", false], ["How it performs per group and on the hardest cases", "كيف يؤدي لكل فئة وعلى أصعب الحالات", true, "Aggregate accuracy hides unequal performance.", "الدقة الإجمالية تخفي الأداء غير المتكافئ."], ["Which programming language it uses", "أي لغة برمجة يستخدم", false]]),
      ] },
    ] },
  ],
  assessments: [
    { titleEn: "AI Fundamentals — module quiz", titleAr: "أساسيات الذكاء الاصطناعي — اختبار الوحدة", kind: "QUIZ", passingScore: 70, questions: [
      mc("Which family of AI learns patterns from labelled examples?", "أي عائلة من الذكاء الاصطناعي تتعلّم الأنماط من أمثلة موسومة؟", [["Rule-based systems", "الأنظمة القائمة على القواعد"], ["Supervised machine learning", "تعلّم الآلة الإشرافي"], ["Search engines", "محركات البحث"], ["Databases", "قواعد البيانات"]], 1, "Supervised learning uses labelled examples.", "التعلّم الإشرافي يستخدم أمثلة موسومة.", { skill: "machine-learning", difficulty: 1 }),
      tf("An LLM that produces fluent text is therefore producing true text.", "النموذج اللغوي الذي ينتج نصاً طليقاً ينتج بالضرورة نصاً صحيحاً.", false, "Fluency is optimised; truth is not guaranteed.", "الطلاقة هي ما يُحسَّن؛ الصحة غير مضمونة.", { skill: "llms", difficulty: 2 }),
      mc("A process is rare, has no captured data and costly mistakes. It is:", "عملية نادرة بلا بيانات مُلتقطة وأخطاؤها مكلفة. هي:", [["A strong AI candidate", "مرشّحة قوية للذكاء الاصطناعي"], ["A weak AI candidate — fix the process first", "مرشّحة ضعيفة — أصلح العملية أولاً"], ["Only suitable for generative AI", "مناسبة للذكاء التوليدي فقط"], ["Impossible to assess", "يستحيل تقييمها"]], 1, "Frequency, data and recoverable mistakes make a good candidate.", "التكرار والبيانات والأخطاء القابلة للتدارك تصنع مرشّحاً جيداً.", { skill: "artificial-intelligence", difficulty: 3 }),
      sa("Name the failure mode where people stop checking a system that is usually right.", "سمِّ نمط الفشل الذي يتوقف فيه الناس عن التحقق من نظام غالباً ما يكون محقاً.", ["automation bias", "تحيز الأتمتة", "تحيّز الأتمتة"], "Automation bias.", "تحيّز الأتمتة.", { skill: "responsible-ai", difficulty: 2 }),
      mc("Why does a separate test set matter?", "لماذا تهم مجموعة اختبار منفصلة؟", [["It speeds up training", "تسرّع التدريب"], ["It estimates performance on unseen data", "تقدّر الأداء على بيانات غير مرئية"], ["It labels the data", "توسم البيانات"], ["It removes parameters", "تزيل المعاملات"]], 1, "Generalisation is measured on unseen data.", "التعميم يُقاس على بيانات غير مرئية.", { skill: "machine-learning", difficulty: 2 }),
    ] },
    { titleEn: "AI Fundamentals — final assessment", titleAr: "أساسيات الذكاء الاصطناعي — الاختبار النهائي", kind: "FINAL", timeLimitMinutes: 20, passingScore: 70, questions: [
      mc("Which is an example of unsupervised learning?", "أي مما يلي مثال على التعلّم غير الإشرافي؟", [["Predicting loan default from labelled history", "التنبؤ بالتعثّر من تاريخ موسوم"], ["Grouping customers into segments with no labels", "تجميع العملاء في شرائح بلا وسوم"], ["A robot learning from rewards", "روبوت يتعلّم من المكافآت"], ["An if-then routing rule", "قاعدة توجيه شرطية"]], 1, "Clustering without labels is unsupervised.", "التجميع بلا وسوم تعلّم غير إشرافي.", { skill: "machine-learning", difficulty: 2 }),
      mc("Grounding an LLM with retrieved documents mainly reduces:", "تأريض النموذج اللغوي بمستندات مسترجعة يقلّل أساساً من:", [["Training cost", "كلفة التدريب"], ["Hallucination", "الهلوسة"], ["Latency", "زمن الاستجابة"], ["Token count", "عدد الرموز"]], 1, "Retrieval supplies facts the model would otherwise guess.", "الاسترجاع يوفّر الحقائق التي كان النموذج سيخمّنها.", { skill: "rag", difficulty: 2 }),
      tf("A named person or team must remain accountable for an AI system's decisions.", "يجب أن يبقى شخص أو فريق محدد مسؤولاً عن قرارات نظام الذكاء الاصطناعي.", true, "Accountability cannot be delegated to a model.", "لا يمكن تفويض المسؤولية إلى النموذج.", { skill: "responsible-ai", difficulty: 1 }),
      mc("Distribution shift means:", "تحوّل التوزيع يعني:", [["The model was trained twice", "دُرّب النموذج مرتين"], ["Real-world data changed after training", "تغيّرت بيانات العالم الحقيقي بعد التدريب"], ["The test set was too small", "كانت مجموعة الاختبار صغيرة"], ["The model has too many parameters", "للنموذج معاملات كثيرة"]], 1, "The world moves; the model stays where it was trained.", "يتغيّر العالم ويبقى النموذج حيث دُرّب.", { skill: "model-evaluation", difficulty: 3 }),
      sa("In one sentence: what does a large language model actually optimise during training?", "في جملة واحدة: ما الذي يُحسِّنه النموذج اللغوي الكبير فعلاً أثناء التدريب؟", ["predict the next token", "next token", "next word", "التنبؤ بالرمز التالي", "الكلمة التالية"], "Predicting the next token.", "التنبؤ بالرمز التالي.", { skill: "llms", difficulty: 2 }),
      mc("Which pattern describes 'forecast water demand per district'?", "أي نمط يصف «توقّع الطلب على المياه لكل منطقة»؟", [["Automate", "أتمتة"], ["Predict", "تنبؤ"], ["Generate", "توليد"], ["Personalise", "تخصيص"]], 1, "Forecasting is the predict pattern.", "التوقّع هو نمط التنبؤ.", { skill: "artificial-intelligence", difficulty: 1 }),
    ] },
  ],
  projects: [{
    slug: "ai-opportunity-map",
    titleEn: "AI opportunity map for one process", titleAr: "خريطة فرص الذكاء الاصطناعي لعملية واحدة",
    briefEn: "Choose one real process in your organisation (or a public service you use) and produce a one-page opportunity map: the process today, the AI family that fits, the data needed, the risks and the human-in-the-loop design.",
    briefAr: "اختر عملية حقيقية واحدة في مؤسستك (أو خدمة عامة تستخدمها) وأنتج خريطة فرص من صفحة واحدة: العملية اليوم، وعائلة الذكاء الاصطناعي المناسبة، والبيانات المطلوبة، والمخاطر، وتصميم دور الإنسان في الحلقة.",
    objectivesEn: ["Apply the four opportunity questions to a real process", "Match a problem to the right AI family", "Design accountability and monitoring before automation"],
    objectivesAr: ["تطبيق أسئلة الفرصة الأربعة على عملية حقيقية", "مطابقة المشكلة بعائلة الذكاء الاصطناعي المناسبة", "تصميم المساءلة والمراقبة قبل الأتمتة"],
    instructionsEn: "1. Describe the process in 5-8 steps and its current metric (time, cost, error rate).\n2. Answer the four opportunity questions with evidence.\n3. Pick the AI family and justify it in one paragraph.\n4. List the data you have and the data you would need.\n5. Describe two risks and how a human stays accountable.\n6. Submit as text (≈600 words) or a link to a document.",
    instructionsAr: "1. صف العملية في 5-8 خطوات ومؤشرها الحالي (الوقت، الكلفة، نسبة الخطأ).\n2. أجب عن أسئلة الفرصة الأربعة بالأدلة.\n3. اختر عائلة الذكاء الاصطناعي وبرّر اختيارك في فقرة.\n4. اذكر البيانات المتوفرة والبيانات التي ستحتاجها.\n5. صف خطرين وكيف يبقى الإنسان مسؤولاً.\n6. سلّم نصاً (نحو 600 كلمة) أو رابط مستند.",
    deliverablesEn: ["Process description with a baseline metric", "Opportunity assessment (four questions)", "AI family choice with justification", "Data inventory", "Risk and accountability plan"],
    deliverablesAr: ["وصف العملية مع مؤشر أساس", "تقييم الفرصة (الأسئلة الأربعة)", "اختيار عائلة الذكاء الاصطناعي مع التبرير", "جرد البيانات", "خطة المخاطر والمساءلة"],
    hours: 6,
    rubric: [
      { id: "process", titleEn: "Process clarity", titleAr: "وضوح العملية", descriptionEn: "Steps and baseline metric are concrete and measurable.", descriptionAr: "الخطوات والمؤشر الأساسي محددة وقابلة للقياس.", weight: 20 },
      { id: "fit", titleEn: "AI fit", titleAr: "ملاءمة الذكاء الاصطناعي", descriptionEn: "The chosen family matches the problem, data and risk tolerance.", descriptionAr: "العائلة المختارة تناسب المشكلة والبيانات وتحمّل المخاطر.", weight: 30 },
      { id: "data", titleEn: "Data realism", titleAr: "واقعية البيانات", descriptionEn: "Available and missing data are identified honestly.", descriptionAr: "البيانات المتوفرة والناقصة محددة بأمانة.", weight: 20 },
      { id: "risk", titleEn: "Risk & accountability", titleAr: "المخاطر والمساءلة", descriptionEn: "Two real risks with a credible human-in-the-loop design.", descriptionAr: "خطران حقيقيان مع تصميم مقنع لدور الإنسان.", weight: 30 },
    ],
  }],
};

export const mlFundamentals: SeedCourse = {
  slug: "machine-learning-fundamentals",
  titleEn: "Machine Learning Fundamentals", titleAr: "أساسيات تعلّم الآلة",
  summaryEn: "Train, evaluate and improve your first models — regression, classification and clustering — with an intuition-first approach.",
  summaryAr: "درّب وقيّم وحسّن نماذجك الأولى — الانحدار والتصنيف والتجميع — بمنهج يبدأ من الحدس.",
  descriptionEn: "You will build a working mental model of how learning algorithms behave: what they can fit, when they overfit, and how to measure them honestly. Every concept is paired with a small hands-on exercise.",
  descriptionAr: "ستبني نموذجاً ذهنياً عملياً لسلوك خوارزميات التعلّم: ما تستطيع ملاءمته، ومتى تفرط في الملاءمة، وكيف تقيسها بأمانة. كل مفهوم مقرون بتمرين عملي قصير.",
  category: "ai", instructor: "amal.alkaabi@nokhba.demo", difficulty: "INTERMEDIATE", hours: 14, cover: "cover-ocean", featured: true,
  outcomesEn: ["Frame a problem as regression, classification or clustering", "Explain bias, variance and overfitting", "Choose and interpret evaluation metrics", "Run a fair train/validation/test protocol"],
  outcomesAr: ["صياغة المشكلة كانحدار أو تصنيف أو تجميع", "شرح التحيّز والتباين والإفراط في الملاءمة", "اختيار مقاييس التقييم وتفسيرها", "تنفيذ بروتوكول عادل للتدريب والتحقق والاختبار"],
  prerequisitesEn: ["AI Fundamentals or equivalent", "Comfort with basic algebra"], prerequisitesAr: ["أساسيات الذكاء الاصطناعي أو ما يعادلها", "إلمام بالجبر الأساسي"],
  skills: ["machine-learning", "model-evaluation", "statistics", "python"], rating: 4.7, ratingCount: 860, enrollmentCount: 3100,
  modules: [
    { titleEn: "Framing problems", titleAr: "صياغة المشكلات", lessons: [
      { slug: "regression-vs-classification", titleEn: "Regression, classification, clustering", titleAr: "الانحدار والتصنيف والتجميع", minutes: 14, skills: ["machine-learning"], freePreview: true, blocks: [
        text(`## Three shapes of question\n\n- **Regression** predicts a number: *How many kilowatt-hours will this district use tomorrow?*\n- **Classification** predicts a category: *Is this transaction fraudulent?*\n- **Clustering** finds groups without labels: *What kinds of commuters use the metro?*\n\nThe shape decides the algorithm, the metric and the way you present results. Getting it wrong at the start wastes weeks.\n\n## Worked example\n\nA municipality wants to reduce complaint-handling time. Tempting framing: "predict handling time" (regression). Better framing after talking to staff: "classify complaints that need a site visit" (classification) — because that decision is what actually delays cases.\n\n> Talk to the people who do the work before you choose the shape.`,
          `## ثلاثة أشكال للسؤال\n\n- **الانحدار** يتنبّأ برقم: *كم كيلوواط-ساعة ستستهلك هذه المنطقة غداً؟*\n- **التصنيف** يتنبّأ بفئة: *هل هذه المعاملة احتيالية؟*\n- **التجميع** يكتشف مجموعات بلا وسوم: *ما أنواع الركاب الذين يستخدمون المترو؟*\n\nالشكل يحدد الخوارزمية والمقياس وطريقة عرض النتائج. الخطأ فيه في البداية يهدر أسابيع.\n\n## مثال عملي\n\nتريد بلدية تقليل زمن معالجة الشكاوى. الصياغة المغرية: «توقّع زمن المعالجة» (انحدار). الصياغة الأفضل بعد الحديث مع الموظفين: «صنّف الشكاوى التي تحتاج زيارة ميدانية» (تصنيف) — لأن هذا القرار هو ما يؤخر الحالات فعلاً.\n\n> تحدّث مع من ينجزون العمل قبل أن تختار الشكل.`),
        check("\"Which of our 40,000 customers are likely to churn next month?\" is:", "«أي عملائنا الأربعين ألفاً يُرجَّح أن يغادروا الشهر القادم؟» هي:", [["Regression", "انحدار", false], ["Classification", "تصنيف", true, "Churn / no churn is a category.", "مغادرة / عدم مغادرة فئة."], ["Clustering", "تجميع", false]]),
      ] },
      { slug: "overfitting-bias-variance", titleEn: "Overfitting, bias and variance", titleAr: "الإفراط في الملاءمة والتحيّز والتباين", minutes: 16, skills: ["machine-learning", "model-evaluation"], blocks: [
        text(`## Memorising vs learning\n\nA model that scores 99% on training data and 71% on test data has **memorised** the training set. This is overfitting: the model captured noise as if it were signal.\n\n## Two sources of error\n\n- **Bias**: the model is too simple to capture the pattern (a straight line through a curve). High bias → underfitting.\n- **Variance**: the model is so flexible it follows the noise. High variance → overfitting.\n\nMore data reduces variance. Simpler models reduce variance but increase bias. **Regularisation** penalises complexity to find the balance.\n\n## Practical signals\n\n| Train score | Test score | Diagnosis |\n|---|---|---|\n| low | low | underfitting (bias) |\n| high | low | overfitting (variance) |\n| high | high | good — now check for leakage |\n\n**Leakage** is when information from the answer sneaks into the features (e.g. "days until account closed" when predicting churn). It produces impossibly good scores that collapse in production.`,
          `## الحفظ مقابل التعلّم\n\nنموذج يحقق 99% على بيانات التدريب و71% على بيانات الاختبار قد **حفظ** مجموعة التدريب. هذا إفراط في الملاءمة: التقط النموذج الضجيج كأنه إشارة.\n\n## مصدران للخطأ\n\n- **التحيّز**: النموذج أبسط من أن يلتقط النمط (خط مستقيم عبر منحنى). تحيّز عالٍ → نقص في الملاءمة.\n- **التباين**: النموذج مرن لدرجة أنه يتبع الضجيج. تباين عالٍ → إفراط في الملاءمة.\n\nالمزيد من البيانات يقلل التباين. النماذج الأبسط تقلل التباين لكنها تزيد التحيّز. **التنظيم** يعاقب التعقيد لإيجاد التوازن.\n\n## إشارات عملية\n\n| نتيجة التدريب | نتيجة الاختبار | التشخيص |\n|---|---|---|\n| منخفضة | منخفضة | نقص ملاءمة (تحيّز) |\n| عالية | منخفضة | إفراط ملاءمة (تباين) |\n| عالية | عالية | جيد — تحقق الآن من التسرّب |\n\n**التسرّب** حين تتسلل معلومات من الإجابة إلى الخصائص (مثل «الأيام حتى إغلاق الحساب» عند التنبؤ بالمغادرة). ينتج نتائج مثالية بشكل مستحيل تنهار في الإنتاج.`),
        check("Train 98%, test 70%. The most likely problem is:", "التدريب 98%، الاختبار 70%. المشكلة الأرجح:", [["Underfitting", "نقص في الملاءمة", false], ["Overfitting", "إفراط في الملاءمة", true, "A large train/test gap signals variance.", "الفجوة الكبيرة بين التدريب والاختبار تشير إلى التباين."], ["Too much data", "بيانات كثيرة جداً", false]]),
      ] },
      { slug: "evaluation-metrics", titleEn: "Evaluation metrics that tell the truth", titleAr: "مقاييس تقييم تقول الحقيقة", minutes: 15, skills: ["model-evaluation", "statistics"], blocks: [
        text(`## Accuracy is a trap\n\nIf 1% of transactions are fraud, a model that says "never fraud" is 99% accurate and useless. For classification, look at the confusion matrix:\n\n- **Precision** = of the cases we flagged, how many were right? (cost of false alarms)\n- **Recall** = of the real cases, how many did we catch? (cost of misses)\n- **F1** balances the two.\n\nChoose the metric from the business cost. Fraud screening with human review can tolerate low precision but needs high recall; automatic account blocking needs high precision.\n\n## For regression\n\n- **MAE** (mean absolute error): average miss, in the original units. Easy to explain.\n- **RMSE**: punishes large misses more. Use when big errors are disproportionately costly.\n\n## Always report per group\n\nA model can be 90% accurate overall and 60% for one nationality or age group. Slice your metrics by the groups that matter for fairness and for the business.`,
          `## الدقة فخ\n\nإذا كان 1% من المعاملات احتيالاً فنموذج يقول «لا احتيال أبداً» دقته 99% وعديم الفائدة. في التصنيف انظر إلى مصفوفة الالتباس:\n\n- **الدقة (Precision)** = من الحالات التي أشّرناها، كم كانت صحيحة؟ (كلفة الإنذارات الكاذبة)\n- **الاستدعاء (Recall)** = من الحالات الحقيقية، كم التقطنا؟ (كلفة الفوات)\n- **F1** يوازن بينهما.\n\nاختر المقياس من الكلفة التجارية. فرز الاحتيال مع مراجعة بشرية يحتمل دقة منخفضة لكنه يحتاج استدعاءً عالياً؛ الحظر التلقائي للحسابات يحتاج دقة عالية.\n\n## للانحدار\n\n- **MAE** (متوسط الخطأ المطلق): متوسط الخطأ بالوحدات الأصلية. سهل الشرح.\n- **RMSE**: يعاقب الأخطاء الكبيرة أكثر. استخدمه حين تكون الأخطاء الكبيرة مكلفة بشكل غير متناسب.\n\n## أبلغ دائماً لكل فئة\n\nقد يكون النموذج دقيقاً بنسبة 90% إجمالاً و60% لجنسية أو فئة عمرية واحدة. قسّم مقاييسك حسب الفئات المهمة للعدالة وللعمل.`),
        check("A screening model where misses are very costly but false alarms are cheap should prioritise:", "نموذج فرز تكون فيه حالات الفوات مكلفة جداً والإنذارات الكاذبة رخيصة يجب أن يعطي الأولوية لـ:", [["Precision", "الدقة", false], ["Recall", "الاستدعاء", true, "Recall measures how many real cases are caught.", "الاستدعاء يقيس كم من الحالات الحقيقية التُقطت."], ["Accuracy", "الدقة الإجمالية", false]]),
      ] },
    ] },
    { titleEn: "Working with data", titleAr: "العمل مع البيانات", lessons: [
      { slug: "features-and-preprocessing", titleEn: "Features and preprocessing", titleAr: "الخصائص والمعالجة المسبقة", minutes: 14, skills: ["machine-learning", "pandas"], blocks: [
        text(`## Models eat numbers\n\nRaw data is rarely model-ready. Typical steps:\n\n1. **Handle missing values** — drop, fill with a statistic, or add an "is missing" flag (missingness is often informative).\n2. **Encode categories** — one-hot encoding for a handful of values; target or embedding encodings for thousands.\n3. **Scale numbers** — many algorithms assume features on similar scales.\n4. **Engineer features** — day-of-week from a timestamp, distance from coordinates, ratio of two columns. Domain knowledge lives here.\n\n## Fit on train only\n\nEvery preprocessing statistic (means for scaling, categories seen) must be computed on the training split and *applied* to validation and test. Computing them on all data leaks information and inflates your scores.\n\n## The pipeline habit\n\nWrap preprocessing and the model into a single pipeline object so the same transformations run identically in training and production.`,
          `## النماذج تأكل الأرقام\n\nنادراً ما تكون البيانات الخام جاهزة للنموذج. الخطوات المعتادة:\n\n1. **معالجة القيم المفقودة** — احذف، أو املأ بإحصائية، أو أضف علامة «مفقود» (الفقدان غالباً معلومة بحد ذاته).\n2. **ترميز الفئات** — الترميز الأحادي لبضع قيم؛ ترميز الهدف أو التضمينات للآلاف.\n3. **تدريج الأرقام** — كثير من الخوارزميات تفترض خصائص بمقاييس متشابهة.\n4. **هندسة الخصائص** — يوم الأسبوع من الطابع الزمني، المسافة من الإحداثيات، نسبة عمودين. هنا تسكن المعرفة بالمجال.\n\n## احسب على التدريب فقط\n\nكل إحصائية معالجة (المتوسطات للتدريج، الفئات المرصودة) يجب حسابها على قسم التدريب ثم *تطبيقها* على التحقق والاختبار. حسابها على كل البيانات يسرّب المعلومات ويضخّم نتائجك.\n\n## عادة خط الأنابيب\n\nاجمع المعالجة والنموذج في كائن خط أنابيب واحد لتُنفَّذ التحويلات نفسها بشكل متطابق في التدريب والإنتاج.`),
        activity("Take any spreadsheet you have (e.g. sales, attendance). List each column and decide: numeric, categorical, timestamp or text — and one engineered feature you could derive.", "خذ أي جدول بيانات لديك (مبيعات، حضور). اذكر كل عمود وقرر: رقمي، فئوي، طابع زمني أم نص — وخاصية مهندسة واحدة يمكنك اشتقاقها.", 12),
      ] },
      { slug: "validation-protocol", titleEn: "A fair validation protocol", titleAr: "بروتوكول تحقق عادل", minutes: 12, skills: ["model-evaluation"], blocks: [
        text(`## Three splits, one purpose each\n\n- **Train**: fit parameters.\n- **Validation**: choose between models and settings (hyperparameters).\n- **Test**: touched once, at the end, to report the final number.\n\nIf you tune on the test set, its score is no longer an honest estimate — you have simply overfitted your *choices* to it.\n\n## Cross-validation\n\nWith little data, rotate the validation fold: split into k parts, train on k−1, validate on the rest, repeat k times, average. It costs compute and buys a stable estimate.\n\n## Time matters\n\nFor anything with a time dimension (demand, prices, traffic), split by time — train on the past, validate on the future. Random shuffling lets the model peek at tomorrow.`,
          `## ثلاثة أقسام، لكل غرض\n\n- **التدريب**: ملاءمة المعاملات.\n- **التحقق**: الاختيار بين النماذج والإعدادات (المعاملات الفائقة).\n- **الاختبار**: يُلمس مرة واحدة في النهاية للإبلاغ عن الرقم النهائي.\n\nإذا ضبطت على مجموعة الاختبار لم تعد نتيجتها تقديراً أميناً — لقد أفرطت في ملاءمة *اختياراتك* لها.\n\n## التحقق المتقاطع\n\nمع بيانات قليلة، دوّر قسم التحقق: قسّم إلى k أجزاء، درّب على k−1، تحقق على الباقي، كرّر k مرات، واحسب المتوسط. يكلّف حساباً ويشتري تقديراً مستقراً.\n\n## الزمن مهم\n\nلأي شيء له بُعد زمني (الطلب، الأسعار، المرور) قسّم حسب الزمن — درّب على الماضي وتحقق على المستقبل. الخلط العشوائي يسمح للنموذج باستراق النظر إلى الغد.`),
        check("You compared five models on the test set and picked the best. What is wrong?", "قارنت خمسة نماذج على مجموعة الاختبار واخترت الأفضل. ما الخطأ؟", [["Nothing", "لا شيء", false], ["The test score is no longer an unbiased estimate", "لم تعد نتيجة الاختبار تقديراً غير متحيّز", true, "Model selection belongs on the validation set.", "اختيار النموذج يخص مجموعة التحقق."], ["Five models are too few", "خمسة نماذج قليلة", false]]),
      ] },
    ] },
  ],
  assessments: [
    { titleEn: "ML Fundamentals — practice quiz", titleAr: "أساسيات تعلّم الآلة — اختبار تدريبي", kind: "PRACTICE", passingScore: 60, questions: [
      mc("Predicting tomorrow's electricity demand in MWh is:", "التنبؤ بالطلب على الكهرباء غداً بالميغاواط-ساعة هو:", [["Classification", "تصنيف"], ["Regression", "انحدار"], ["Clustering", "تجميع"], ["Reinforcement", "تعزيزي"]], 1, "A continuous number → regression.", "رقم متصل → انحدار.", { skill: "machine-learning", difficulty: 1 }),
      mc("High variance typically shows as:", "التباين العالي يظهر عادةً كـ:", [["Low train, low test", "تدريب منخفض، اختبار منخفض"], ["High train, low test", "تدريب عالٍ، اختبار منخفض"], ["Low train, high test", "تدريب منخفض، اختبار عالٍ"], ["Equal scores", "نتائج متساوية"]], 1, "Memorising the training set.", "حفظ مجموعة التدريب.", { skill: "model-evaluation", difficulty: 2 }),
      tf("Scaling statistics should be computed on the full dataset before splitting.", "يجب حساب إحصائيات التدريج على كامل البيانات قبل التقسيم.", false, "That leaks test information into training.", "هذا يسرّب معلومات الاختبار إلى التدريب.", { skill: "machine-learning", difficulty: 3 }),
      sa("Which metric answers 'of the real positives, how many did we catch'?", "أي مقياس يجيب عن «من الإيجابيات الحقيقية، كم التقطنا»؟", ["recall", "الاستدعاء", "استدعاء"], "Recall.", "الاستدعاء.", { skill: "model-evaluation", difficulty: 2 }),
      mc("For a demand forecast, the right split is:", "لتوقّع الطلب، التقسيم الصحيح هو:", [["Random shuffle", "خلط عشوائي"], ["By time: past → future", "حسب الزمن: الماضي → المستقبل"], ["By customer name", "حسب اسم العميل"], ["No split", "بلا تقسيم"]], 1, "Never let the model peek at the future.", "لا تدع النموذج يسترق النظر إلى المستقبل.", { skill: "model-evaluation", difficulty: 2 }),
    ] },
  ],
  projects: [{
    slug: "churn-model-report",
    titleEn: "Model evaluation report", titleAr: "تقرير تقييم نموذج",
    briefEn: "Using the provided customer-churn dataset (or one of your own), train two models, evaluate them honestly and write a decision memo recommending one — or neither.",
    briefAr: "باستخدام مجموعة بيانات مغادرة العملاء المرفقة (أو بياناتك)، درّب نموذجين وقيّمهما بأمانة واكتب مذكرة قرار توصي بأحدهما — أو بلا أحد.",
    objectivesEn: ["Run a fair train/validation/test protocol", "Choose metrics from business cost", "Communicate results to a non-technical decision maker"],
    objectivesAr: ["تنفيذ بروتوكول عادل للتدريب والتحقق والاختبار", "اختيار المقاييس من الكلفة التجارية", "إيصال النتائج لصانع قرار غير تقني"],
    instructionsEn: "1. Frame the problem and state the business cost of a miss vs a false alarm.\n2. Preprocess with a pipeline; fit statistics on train only.\n3. Train a simple baseline and one stronger model.\n4. Report precision, recall, F1 overall and per customer segment.\n5. Write a 1-page memo: recommendation, risks, monitoring plan.\n6. Submit a repository link or notebook plus the memo text.",
    instructionsAr: "1. صِغ المشكلة واذكر الكلفة التجارية للفوات مقابل الإنذار الكاذب.\n2. عالج البيانات بخط أنابيب؛ احسب الإحصائيات على التدريب فقط.\n3. درّب نموذجاً أساسياً بسيطاً ونموذجاً أقوى.\n4. أبلغ عن الدقة والاستدعاء وF1 إجمالاً ولكل شريحة عملاء.\n5. اكتب مذكرة من صفحة: التوصية، المخاطر، خطة المراقبة.\n6. سلّم رابط مستودع أو دفتر ملاحظات مع نص المذكرة.",
    deliverablesEn: ["Notebook or repository", "Metrics table overall and per segment", "One-page decision memo"],
    deliverablesAr: ["دفتر ملاحظات أو مستودع", "جدول المقاييس إجمالاً ولكل شريحة", "مذكرة قرار من صفحة"],
    resources: [{ labelEn: "Telco churn dataset (Kaggle)", labelAr: "بيانات مغادرة عملاء الاتصالات (Kaggle)", url: "https://www.kaggle.com/datasets/blastchar/telco-customer-churn" }],
    hours: 10,
    rubric: [
      { id: "protocol", titleEn: "Validation protocol", titleAr: "بروتوكول التحقق", descriptionEn: "Splits are correct, no leakage, statistics fit on train.", descriptionAr: "الأقسام صحيحة، بلا تسرّب، الإحصائيات محسوبة على التدريب.", weight: 30 },
      { id: "metrics", titleEn: "Metric choice & reporting", titleAr: "اختيار المقاييس والإبلاغ", descriptionEn: "Metrics follow business cost and are reported per segment.", descriptionAr: "المقاييس تتبع الكلفة التجارية ومُبلَّغ عنها لكل شريحة.", weight: 30 },
      { id: "memo", titleEn: "Decision memo", titleAr: "مذكرة القرار", descriptionEn: "Clear recommendation, honest limitations, monitoring plan.", descriptionAr: "توصية واضحة، حدود صريحة، خطة مراقبة.", weight: 25 },
      { id: "code", titleEn: "Reproducibility", titleAr: "قابلية إعادة الإنتاج", descriptionEn: "Someone else can run it and get the same numbers.", descriptionAr: "يمكن لشخص آخر تشغيله والحصول على الأرقام نفسها.", weight: 15 },
    ],
  }],
};
