import { type SeedCourse, text, check, activity, code, mc, tf, sa } from "./types";

export const pythonEssentials: SeedCourse = {
  slug: "python-programming-essentials",
  titleEn: "Python Programming Essentials", titleAr: "أساسيات البرمجة بلغة بايثون",
  summaryEn: "Write real Python from day one: variables, control flow, functions, data structures and files — with graded exercises.",
  summaryAr: "اكتب بايثون حقيقية من اليوم الأول: المتغيرات والتحكم بالتدفق والدوال وهياكل البيانات والملفات — مع تمارين مقيَّمة.",
  descriptionEn: "The programming foundation for every data and AI track. Short lessons, immediate practice in the built-in code environment, and an AI coach that hints before it solves.",
  descriptionAr: "الأساس البرمجي لكل مسارات البيانات والذكاء الاصطناعي. دروس قصيرة، وتدريب فوري في بيئة الكود المدمجة، ومدرّب ذكي يلمّح قبل أن يحل.",
  category: "programming", instructor: "layla.hassan@nokhba.demo", difficulty: "BEGINNER", hours: 12, cover: "cover-slate", featured: true,
  outcomesEn: ["Use variables, types and control flow", "Write and test functions", "Work with lists, dictionaries and files", "Read errors and debug systematically"],
  outcomesAr: ["استخدام المتغيرات والأنواع والتحكم بالتدفق", "كتابة الدوال واختبارها", "التعامل مع القوائم والقواميس والملفات", "قراءة الأخطاء وتصحيحها بشكل منهجي"],
  skills: ["python", "programming-fundamentals", "problem-solving"], rating: 4.8, ratingCount: 3120, enrollmentCount: 9800,
  modules: [
    { titleEn: "First programs", titleAr: "البرامج الأولى", lessons: [
      { slug: "variables-and-types", titleEn: "Variables and types", titleAr: "المتغيرات والأنواع", minutes: 12, skills: ["python"], freePreview: true, blocks: [
        text(`## Naming values\n\n\`\`\`python\ncity = "Al Ain"          # str\npopulation = 846_000     # int\ngrowth = 0.032           # float\nis_capital = False       # bool\n\`\`\`\n\nPython infers the type from the value. \`type(city)\` tells you what you have. Converting: \`int("42")\`, \`str(3.5)\`, \`float("2.5")\`.\n\n## f-strings\n\n\`\`\`python\nprint(f"{city} will grow by {growth:.1%} next year")\n\`\`\`\n\n## Common mistakes\n\n- Adding a string and a number: \`"Age: " + 30\` → TypeError. Convert first.\n- Using \`=\` when you mean \`==\`.\n- Forgetting that names are case-sensitive: \`City\` and \`city\` are different.`,
          `## تسمية القيم\n\n\`\`\`python\ncity = "Al Ain"          # str\npopulation = 846_000     # int\ngrowth = 0.032           # float\nis_capital = False       # bool\n\`\`\`\n\nتستنتج بايثون النوع من القيمة. \`type(city)\` تخبرك بما لديك. التحويل: \`int("42")\`، \`str(3.5)\`، \`float("2.5")\`.\n\n## سلاسل f\n\n\`\`\`python\nprint(f"{city} will grow by {growth:.1%} next year")\n\`\`\`\n\n## أخطاء شائعة\n\n- جمع سلسلة ورقم: \`"Age: " + 30\` ← TypeError. حوّل أولاً.\n- استخدام \`=\` حين تقصد \`==\`.\n- نسيان أن الأسماء حساسة لحالة الأحرف: \`City\` و\`city\` مختلفان.`),
        check("`int(\"42\") + 1` evaluates to:", "`int(\"42\") + 1` تساوي:", [["\"421\"", "\"421\"", false], ["43", "43", true, "int() converts the string, then arithmetic applies.", "int() تحوّل السلسلة ثم يُطبَّق الحساب."], ["TypeError", "TypeError", false]]),
      ] },
      { slug: "control-flow", titleEn: "Conditions and loops", titleAr: "الشروط والحلقات", minutes: 14, skills: ["python", "programming-fundamentals"], blocks: [
        text(`## Deciding\n\n\`\`\`python\nif temp >= 45:\n    status = "extreme"\nelif temp >= 38:\n    status = "hot"\nelse:\n    status = "normal"\n\`\`\`\n\nIndentation *is* the syntax — four spaces, consistently.\n\n## Repeating\n\n\`\`\`python\nfor reading in readings:\n    total += reading\n\nwhile attempts < 3:\n    attempts += 1\n\`\`\`\n\nUse \`for\` when you know what you iterate over; \`while\` when you loop until a condition changes. \`break\` exits early; \`continue\` skips to the next iteration.\n\n## Ranges and enumerate\n\n\`range(5)\` gives 0..4. \`enumerate(items)\` gives (index, item) pairs — reach for it instead of manual counters.`,
          `## اتخاذ القرار\n\n\`\`\`python\nif temp >= 45:\n    status = "extreme"\nelif temp >= 38:\n    status = "hot"\nelse:\n    status = "normal"\n\`\`\`\n\nالمسافة البادئة *هي* التركيب — أربع مسافات باتساق.\n\n## التكرار\n\n\`\`\`python\nfor reading in readings:\n    total += reading\n\nwhile attempts < 3:\n    attempts += 1\n\`\`\`\n\nاستخدم \`for\` حين تعرف ما تكرر عليه؛ و\`while\` حين تكرر حتى يتغير شرط. \`break\` تخرج مبكراً؛ \`continue\` تقفز إلى التكرار التالي.\n\n## المدى والترقيم\n\n\`range(5)\` تعطي 0..4. \`enumerate(items)\` تعطي أزواج (الفهرس، العنصر) — استخدمها بدل العدّادات اليدوية.`),
        code({ language: "python", instructionsEn: "Write `solve(readings)` that returns how many temperature readings are 40 or above.", instructionsAr: "اكتب `solve(readings)` التي تعيد عدد قراءات الحرارة التي تساوي 40 أو أكثر.", starterCode: "def solve(readings):\n    count = 0\n    # TODO: count readings >= 40\n    return count\n", solution: "def solve(readings):\n    count = 0\n    for r in readings:\n        if r >= 40:\n            count += 1\n    return count\n", tests: [{ name: "mixed", args: [[38, 41, 45, 39, 40]], expected: 3 }, { name: "none", args: [[30, 31]], expected: 0 }, { name: "empty", args: [[]], expected: 0 }] }),
      ] },
      { slug: "functions", titleEn: "Functions", titleAr: "الدوال", minutes: 15, skills: ["python", "problem-solving"], blocks: [
        text(`## Name a piece of behaviour\n\n\`\`\`python\ndef vat(amount, rate=0.05):\n    """Return the VAT for an amount (UAE default 5%)."""\n    return round(amount * rate, 2)\n\`\`\`\n\n- Parameters can have defaults.\n- \`return\` sends a value back; without it the function returns \`None\`.\n- The docstring explains *what* and *why*; the AI coach reads it too.\n\n## Small and testable\n\nA function should do one thing. If you cannot name it with a verb and an object (\`calculate_vat\`, \`load_readings\`) it is doing too much. Test with concrete inputs: \`assert vat(100) == 5.0\`.`,
          `## سمِّ سلوكاً\n\n\`\`\`python\ndef vat(amount, rate=0.05):\n    """Return the VAT for an amount (UAE default 5%)."""\n    return round(amount * rate, 2)\n\`\`\`\n\n- يمكن للمعاملات أن تأخذ قيماً افتراضية.\n- \`return\` تعيد قيمة؛ بدونها تعيد الدالة \`None\`.\n- سلسلة التوثيق تشرح *ماذا* و*لماذا*؛ يقرأها المدرّب الذكي أيضاً.\n\n## صغيرة وقابلة للاختبار\n\nيجب أن تفعل الدالة شيئاً واحداً. إذا لم تستطع تسميتها بفعل ومفعول (\`calculate_vat\`، \`load_readings\`) فهي تفعل الكثير. اختبر بمدخلات ملموسة: \`assert vat(100) == 5.0\`.`),
        code({ language: "python", instructionsEn: "Write `solve(amount, rate)` returning the total including VAT, rounded to 2 decimals. `rate` defaults to 0.05.", instructionsAr: "اكتب `solve(amount, rate)` التي تعيد الإجمالي شاملاً الضريبة مقرّباً إلى منزلتين. القيمة الافتراضية لـ `rate` هي 0.05.", starterCode: "def solve(amount, rate=0.05):\n    # TODO\n    pass\n", solution: "def solve(amount, rate=0.05):\n    return round(amount * (1 + rate), 2)\n", tests: [{ name: "default rate", args: [100], expected: 105.0 }, { name: "custom rate", args: [200, 0.1], expected: 220.0 }, { name: "rounding", args: [33.333], expected: 35.0 }] }),
      ] },
    ] },
    { titleEn: "Data structures", titleAr: "هياكل البيانات", lessons: [
      { slug: "lists-and-dicts", titleEn: "Lists and dictionaries", titleAr: "القوائم والقواميس", minutes: 16, skills: ["python"], blocks: [
        text(`## Lists: ordered collections\n\n\`\`\`python\nemirates = ["Abu Dhabi", "Dubai", "Sharjah"]\nemirates.append("Ajman")\nemirates[0]          # "Abu Dhabi"\nlen(emirates)        # 4\n[e.upper() for e in emirates if len(e) > 5]   # list comprehension\n\`\`\`\n\n## Dictionaries: key → value\n\n\`\`\`python\npopulation = {"Dubai": 3_600_000, "Sharjah": 1_800_000}\npopulation["Ajman"] = 540_000\npopulation.get("Fujairah", 0)     # safe lookup\nfor city, n in population.items():\n    print(city, n)\n\`\`\`\n\nUse a list when order matters and items are alike; a dict when you look things up by name. Sets (\`{...}\`) hold unique items and make membership tests fast.`,
          `## القوائم: مجموعات مرتبة\n\n\`\`\`python\nemirates = ["Abu Dhabi", "Dubai", "Sharjah"]\nemirates.append("Ajman")\nemirates[0]          # "Abu Dhabi"\nlen(emirates)        # 4\n[e.upper() for e in emirates if len(e) > 5]   # list comprehension\n\`\`\`\n\n## القواميس: مفتاح ← قيمة\n\n\`\`\`python\npopulation = {"Dubai": 3_600_000, "Sharjah": 1_800_000}\npopulation["Ajman"] = 540_000\npopulation.get("Fujairah", 0)     # بحث آمن\nfor city, n in population.items():\n    print(city, n)\n\`\`\`\n\nاستخدم القائمة حين يهم الترتيب والعناصر متشابهة؛ والقاموس حين تبحث بالاسم. المجموعات (\`{...}\`) تحفظ عناصر فريدة وتجعل اختبار العضوية سريعاً.`),
        code({ language: "python", instructionsEn: "Write `solve(records)` where records is a list of `{\"city\": str, \"visits\": int}` dicts. Return a dict of total visits per city.", instructionsAr: "اكتب `solve(records)` حيث records قائمة قواميس `{\"city\": str, \"visits\": int}`. أعد قاموساً بإجمالي الزيارات لكل مدينة.", starterCode: "def solve(records):\n    totals = {}\n    # TODO\n    return totals\n", solution: "def solve(records):\n    totals = {}\n    for r in records:\n        totals[r[\"city\"]] = totals.get(r[\"city\"], 0) + r[\"visits\"]\n    return totals\n", tests: [{ name: "aggregates", args: [[{ city: "Dubai", visits: 2 }, { city: "Dubai", visits: 3 }, { city: "Ajman", visits: 1 }]], expected: { Dubai: 5, Ajman: 1 } }, { name: "empty", args: [[]], expected: {} }] }),
      ] },
      { slug: "errors-and-debugging", titleEn: "Errors and debugging", titleAr: "الأخطاء والتصحيح", minutes: 12, skills: ["problem-solving", "python"], blocks: [
        text(`## Read the traceback bottom-up\n\nThe last line names the error (\`KeyError: 'Fujairah'\`); the lines above show where. Start there, not at the top.\n\n## The debugging loop\n\n1. Reproduce with the smallest input that fails.\n2. Form a hypothesis ("the key is missing when the city is new").\n3. Check it with a \`print\` or a breakpoint.\n4. Fix, then re-run *all* tests.\n\n## Handling expected failures\n\n\`\`\`python\ntry:\n    value = int(text)\nexcept ValueError:\n    value = 0\n\`\`\`\n\nCatch only the error you expect. A bare \`except:\` hides real bugs.`,
          `## اقرأ تتبّع الخطأ من الأسفل للأعلى\n\nالسطر الأخير يسمّي الخطأ (\`KeyError: 'Fujairah'\`)؛ والأسطر فوقه تبيّن الموضع. ابدأ من هناك لا من الأعلى.\n\n## حلقة التصحيح\n\n1. أعد إنتاج الخطأ بأصغر مدخل يفشل.\n2. كوّن فرضية («المفتاح مفقود حين تكون المدينة جديدة»).\n3. تحقق منها بـ \`print\` أو نقطة توقف.\n4. أصلح ثم أعد تشغيل *كل* الاختبارات.\n\n## التعامل مع الفشل المتوقع\n\n\`\`\`python\ntry:\n    value = int(text)\nexcept ValueError:\n    value = 0\n\`\`\`\n\nالتقط الخطأ الذي تتوقعه فقط. \`except:\` العارية تخفي الأخطاء الحقيقية.`),
        check("Where should you start reading a Python traceback?", "من أين تبدأ قراءة تتبّع الخطأ في بايثون؟", [["The first line", "السطر الأول", false], ["The last line, which names the error", "السطر الأخير الذي يسمّي الخطأ", true, "Then walk up to the location.", "ثم اصعد إلى الموضع."], ["The middle", "المنتصف", false]]),
      ] },
    ] },
  ],
  assessments: [
    { titleEn: "Python Essentials — final assessment", titleAr: "أساسيات بايثون — الاختبار النهائي", kind: "FINAL", timeLimitMinutes: 20, passingScore: 70, questions: [
      mc("What does `population.get(\"X\", 0)` return when X is absent?", "ماذا تعيد `population.get(\"X\", 0)` حين لا يوجد X؟", [["KeyError", "KeyError"], ["0", "0"], ["None", "None"], ["\"X\"", "\"X\""]], 1, "get() returns the default.", "get() تعيد القيمة الافتراضية.", { skill: "python", difficulty: 1 }),
      tf("A function without a return statement returns None.", "الدالة بلا عبارة return تعيد None.", true, "Implicit None.", "None ضمنياً.", { skill: "python", difficulty: 1 }),
      sa("Which loop keyword exits a loop immediately?", "أي كلمة مفتاحية تخرج من الحلقة فوراً؟", ["break"], "break.", "break.", { skill: "programming-fundamentals", difficulty: 1 }),
      mc("`[x * 2 for x in [1, 2, 3] if x > 1]` equals:", "`[x * 2 for x in [1, 2, 3] if x > 1]` تساوي:", [["[2, 4, 6]", "[2, 4, 6]"], ["[4, 6]", "[4, 6]"], ["[1, 2]", "[1, 2]"], ["[]", "[]"]], 1, "Filter then map.", "تصفية ثم تحويل.", { skill: "python", difficulty: 3 }),
      mc("A bare `except:` is discouraged because:", "تُستهجن `except:` العارية لأنها:", [["It is slow", "بطيئة"], ["It hides unexpected bugs", "تخفي الأخطاء غير المتوقعة"], ["It is a syntax error", "خطأ تركيبي"], ["It only catches ValueError", "تلتقط ValueError فقط"]], 1, "Catch what you expect.", "التقط ما تتوقعه.", { skill: "problem-solving", difficulty: 2 }),
    ] },
  ],
};

export const dataAnalytics: SeedCourse = {
  slug: "data-analytics-with-python",
  titleEn: "Data Analytics with Python", titleAr: "تحليل البيانات باستخدام بايثون",
  summaryEn: "Load, clean, analyse and visualise real datasets with pandas — and tell a decision-maker what they mean.",
  summaryAr: "حمّل ونظّف وحلّل وصوّر مجموعات بيانات حقيقية باستخدام pandas — وأخبر صانع القرار بما تعنيه.",
  descriptionEn: "From a messy CSV to a one-page insight brief. You will practise the analyst's loop — question, data, analysis, chart, story — on open UAE-style datasets.",
  descriptionAr: "من ملف CSV فوضوي إلى موجز رؤى من صفحة واحدة. ستتدرب على حلقة المحلل — السؤال، البيانات، التحليل، الرسم، القصة — على بيانات مفتوحة بنمط إماراتي.",
  category: "data", instructor: "layla.hassan@nokhba.demo", difficulty: "BEGINNER", hours: 14, cover: "cover-sand", featured: true,
  outcomesEn: ["Load and clean tabular data with pandas", "Aggregate and join datasets", "Choose the right chart and avoid misleading ones", "Write an insight brief for decision makers"],
  outcomesAr: ["تحميل وتنظيف البيانات الجدولية بـ pandas", "تجميع البيانات وربطها", "اختيار الرسم المناسب وتجنب المضلل", "كتابة موجز رؤى لصنّاع القرار"],
  prerequisitesEn: ["Python Programming Essentials"], prerequisitesAr: ["أساسيات البرمجة بلغة بايثون"],
  skills: ["data-analysis", "pandas", "data-visualization", "statistics", "data-storytelling"], rating: 4.7, ratingCount: 1480, enrollmentCount: 4300,
  modules: [
    { titleEn: "The analyst's loop", titleAr: "حلقة المحلل", lessons: [
      { slug: "loading-and-cleaning", titleEn: "Loading and cleaning data", titleAr: "تحميل البيانات وتنظيفها", minutes: 16, skills: ["pandas", "data-analysis"], freePreview: true, blocks: [
        text(`## First look\n\n\`\`\`python\nimport pandas as pd\ndf = pd.read_csv("permits.csv")\ndf.shape, df.dtypes\ndf.head()\ndf.isna().sum()\n\`\`\`\n\n## Typical cleaning\n\n- Parse dates: \`pd.to_datetime(df["issued"], errors="coerce")\`.\n- Normalise text: \`df["emirate"].str.strip().str.title()\`.\n- Handle missing values deliberately — and record what you did.\n- Remove exact duplicates: \`df.drop_duplicates()\`.\n\n## A cleaning log\n\nKeep a short list: what you changed, why, how many rows were affected. Analyses without a cleaning log are not reproducible, and reviewers will (rightly) distrust them.`,
          `## النظرة الأولى\n\n\`\`\`python\nimport pandas as pd\ndf = pd.read_csv("permits.csv")\ndf.shape, df.dtypes\ndf.head()\ndf.isna().sum()\n\`\`\`\n\n## التنظيف المعتاد\n\n- تحليل التواريخ: \`pd.to_datetime(df["issued"], errors="coerce")\`.\n- توحيد النص: \`df["emirate"].str.strip().str.title()\`.\n- معالجة القيم المفقودة عمداً — وتسجيل ما فعلت.\n- إزالة التكرارات التامة: \`df.drop_duplicates()\`.\n\n## سجل التنظيف\n\nاحتفظ بقائمة قصيرة: ما غيّرته، ولماذا، وكم صفاً تأثر. التحليلات بلا سجل تنظيف غير قابلة لإعادة الإنتاج، وسيرتاب المراجعون فيها (بحق).`),
        code({ language: "python", instructionsEn: "Without pandas: write `solve(rows)` that takes a list of emirate names with inconsistent spacing/case (e.g. \"  dubai \") and returns a sorted list of unique, title-cased names.", instructionsAr: "بدون pandas: اكتب `solve(rows)` التي تأخذ قائمة أسماء إمارات بمسافات وحالات أحرف غير متسقة (مثل \"  dubai \") وتعيد قائمة مرتبة من الأسماء الفريدة بحالة العنوان.", starterCode: "def solve(rows):\n    # TODO\n    pass\n", solution: "def solve(rows):\n    return sorted({r.strip().title() for r in rows})\n", tests: [{ name: "normalises", args: [["  dubai ", "DUBAI", "Sharjah", "sharjah "]], expected: ["Dubai", "Sharjah"] }, { name: "empty", args: [[]], expected: [] }] }),
      ] },
      { slug: "aggregating-and-joining", titleEn: "Aggregating and joining", titleAr: "التجميع والربط", minutes: 15, skills: ["pandas", "sql"], blocks: [
        text(`## Group, then summarise\n\n\`\`\`python\nby_emirate = df.groupby("emirate")["amount"].agg(["count", "sum", "median"])\nmonthly = df.set_index("issued").resample("M")["amount"].sum()\n\`\`\`\n\nMedian resists outliers; mean does not. Report both when the distribution is skewed (it usually is).\n\n## Joining tables\n\n\`\`\`python\nmerged = permits.merge(population, on="emirate", how="left")\nmerged["per_1000"] = merged["count"] / merged["population"] * 1000\n\`\`\`\n\nAlways check row counts before and after a join. A silent many-to-many join is the most common way to double-count.\n\n## SQL equivalence\n\n\`groupby\` ≈ \`GROUP BY\`; \`merge\` ≈ \`JOIN\`. Analysts move between the two daily; learn both vocabularies.`,
          `## جمّع ثم لخّص\n\n\`\`\`python\nby_emirate = df.groupby("emirate")["amount"].agg(["count", "sum", "median"])\nmonthly = df.set_index("issued").resample("M")["amount"].sum()\n\`\`\`\n\nالوسيط يقاوم القيم الشاذة؛ المتوسط لا. أبلغ عن الاثنين حين يكون التوزيع ملتوياً (وهو كذلك عادةً).\n\n## ربط الجداول\n\n\`\`\`python\nmerged = permits.merge(population, on="emirate", how="left")\nmerged["per_1000"] = merged["count"] / merged["population"] * 1000\n\`\`\`\n\nتحقق دائماً من عدد الصفوف قبل الربط وبعده. الربط الصامت متعدد-إلى-متعدد أكثر طرق العدّ المزدوج شيوعاً.\n\n## المكافئ في SQL\n\n\`groupby\` ≈ \`GROUP BY\`؛ \`merge\` ≈ \`JOIN\`. ينتقل المحللون بين الاثنين يومياً؛ تعلّم المفردتين.`),
        check("Row count jumped from 10,000 to 34,000 after a merge. Most likely:", "قفز عدد الصفوف من 10,000 إلى 34,000 بعد الربط. الأرجح:", [["The data grew", "نمت البيانات", false], ["A many-to-many join duplicated rows", "ربط متعدد-إلى-متعدد كرّر الصفوف", true, "Check keys for uniqueness before joining.", "تحقق من تفرّد المفاتيح قبل الربط."], ["pandas has a bug", "خلل في pandas", false]]),
      ] },
      { slug: "charts-that-tell-the-truth", titleEn: "Charts that tell the truth", titleAr: "رسوم تقول الحقيقة", minutes: 13, skills: ["data-visualization", "data-storytelling"], blocks: [
        text(`## Match the chart to the question\n\n| Question | Chart |\n|---|---|\n| How does it change over time? | line |\n| How do categories compare? | bar (sorted) |\n| How is it distributed? | histogram / box |\n| Are two things related? | scatter |\n\n## Rules that prevent lies\n\n- Bars start at zero. Always.\n- One message per chart; the title states it ("Permits fell 18% after the fee change").\n- Label units and sources.\n- Avoid pie charts beyond three slices; avoid 3D entirely.\n- For Arabic audiences, mirror the layout: legends and axes read right-to-left.\n\n## The insight brief\n\nOne page: the question, the answer in one sentence, one chart, three supporting facts, the caveats, and the recommended next step.`,
          `## طابق الرسم مع السؤال\n\n| السؤال | الرسم |\n|---|---|\n| كيف يتغيّر عبر الزمن؟ | خطي |\n| كيف تُقارن الفئات؟ | أعمدة (مرتبة) |\n| كيف يتوزّع؟ | مدرّج تكراري / صندوقي |\n| هل يرتبط شيئان؟ | مبعثر |\n\n## قواعد تمنع الكذب\n\n- تبدأ الأعمدة من الصفر. دائماً.\n- رسالة واحدة لكل رسم؛ والعنوان يصرّح بها («انخفضت التصاريح 18% بعد تغيير الرسوم»).\n- سمِّ الوحدات والمصادر.\n- تجنب الرسوم الدائرية فوق ثلاث شرائح؛ وتجنب ثلاثية الأبعاد كلياً.\n- للجمهور العربي اعكس التخطيط: تُقرأ المفاتيح والمحاور من اليمين إلى اليسار.\n\n## موجز الرؤى\n\nصفحة واحدة: السؤال، الإجابة في جملة، رسم واحد، ثلاث حقائق داعمة، التحفظات، والخطوة التالية الموصى بها.`),
        activity("Find one chart in a news article or report. Identify its question, check the zero baseline, and rewrite its title as a one-sentence message.", "اعثر على رسم في مقال إخباري أو تقرير. حدد سؤاله، وتحقق من خط الأساس الصفري، وأعد كتابة عنوانه كرسالة من جملة.", 10),
      ] },
    ] },
  ],
  assessments: [
    { titleEn: "Data Analytics — quiz", titleAr: "تحليل البيانات — اختبار", kind: "QUIZ", passingScore: 70, questions: [
      mc("Which summary statistic resists outliers?", "أي إحصائية تلخيصية تقاوم القيم الشاذة؟", [["Mean", "المتوسط"], ["Median", "الوسيط"], ["Sum", "المجموع"], ["Max", "الأقصى"]], 1, "The median is robust.", "الوسيط متين.", { skill: "statistics", difficulty: 1 }),
      tf("Bar charts may start above zero to emphasise differences.", "يجوز أن تبدأ الأعمدة فوق الصفر لإبراز الفروق.", false, "Bars must start at zero.", "يجب أن تبدأ الأعمدة من الصفر.", { skill: "data-visualization", difficulty: 1 }),
      sa("Which pandas method combines two tables on a key?", "أي دالة في pandas تدمج جدولين على مفتاح؟", ["merge", "join"], "merge (or join).", "merge (أو join).", { skill: "pandas", difficulty: 1 }),
      mc("To compare categories, the recommended chart is:", "لمقارنة الفئات، الرسم الموصى به:", [["Pie with 8 slices", "دائري بثماني شرائح"], ["Sorted bar chart", "أعمدة مرتبة"], ["3D column", "أعمدة ثلاثية الأبعاد"], ["Scatter", "مبعثر"]], 1, "Sorted bars make comparison easy.", "الأعمدة المرتبة تسهّل المقارنة.", { skill: "data-visualization", difficulty: 2 }),
    ] },
  ],
  projects: [{
    slug: "insight-brief",
    titleEn: "One-page insight brief", titleAr: "موجز رؤى من صفحة واحدة",
    briefEn: "Choose an open dataset (e.g. from bayanat.ae or data.gov.ae), answer one decision-relevant question, and deliver a one-page brief with a single honest chart.",
    briefAr: "اختر مجموعة بيانات مفتوحة (من bayanat.ae أو data.gov.ae مثلاً)، وأجب عن سؤال واحد متصل بالقرار، وسلّم موجزاً من صفحة مع رسم واحد أمين.",
    objectivesEn: ["Apply the analyst's loop end to end", "Keep a cleaning log", "Communicate one insight clearly"],
    objectivesAr: ["تطبيق حلقة المحلل من البداية للنهاية", "الاحتفاظ بسجل تنظيف", "إيصال رؤية واحدة بوضوح"],
    instructionsEn: "Submit the notebook link and the brief text (question, one-sentence answer, chart description, three facts, caveats, next step).",
    instructionsAr: "سلّم رابط الدفتر ونص الموجز (السؤال، الإجابة في جملة، وصف الرسم، ثلاث حقائق، التحفظات، الخطوة التالية).",
    deliverablesEn: ["Notebook with cleaning log", "One-page brief"], deliverablesAr: ["دفتر مع سجل تنظيف", "موجز من صفحة"],
    resources: [{ labelEn: "UAE open data portal", labelAr: "بوابة البيانات المفتوحة الإماراتية", url: "https://bayanat.ae" }],
    hours: 8,
    rubric: [
      { id: "question", titleEn: "Decision-relevant question", titleAr: "سؤال متصل بالقرار", descriptionEn: "The question matters to a real decision maker.", descriptionAr: "السؤال يهم صانع قرار حقيقياً.", weight: 20 },
      { id: "cleaning", titleEn: "Cleaning log", titleAr: "سجل التنظيف", descriptionEn: "Every transformation is recorded with row counts.", descriptionAr: "كل تحويل مسجّل مع عدد الصفوف.", weight: 25 },
      { id: "chart", titleEn: "Honest chart", titleAr: "رسم أمين", descriptionEn: "Right chart type, zero baseline, labelled, one message.", descriptionAr: "نوع رسم صحيح، خط أساس صفري، موسوم، رسالة واحدة.", weight: 30 },
      { id: "story", titleEn: "Brief clarity", titleAr: "وضوح الموجز", descriptionEn: "Answer first; facts support; caveats honest.", descriptionAr: "الإجابة أولاً؛ الحقائق داعمة؛ التحفظات صادقة.", weight: 25 },
    ],
  }],
};

export const cyberFoundations: SeedCourse = {
  slug: "cybersecurity-foundations",
  titleEn: "Cybersecurity Foundations", titleAr: "أساسيات الأمن السيبراني",
  summaryEn: "Think like a defender: threats, controls, identity, incident response and the habits that stop most attacks.",
  summaryAr: "فكّر كمدافع: التهديدات والضوابط والهوية والاستجابة للحوادث والعادات التي توقف معظم الهجمات.",
  descriptionEn: "A practical foundation for analysts, engineers and managers. You will model threats for a real system, apply the CIA triad, design identity and access controls, and run a tabletop incident exercise aligned with UAE information-assurance practice.",
  descriptionAr: "أساس عملي للمحللين والمهندسين والمديرين. ستنمذج التهديدات لنظام حقيقي، وتطبّق ثالوث CIA، وتصمّم ضوابط الهوية والوصول، وتنفّذ تمرين استجابة نظرياً متوافقاً مع ممارسات ضمان المعلومات في الإمارات.",
  category: "cybersecurity", instructor: "khalid.rahman@nokhba.demo", difficulty: "BEGINNER", hours: 12, cover: "cover-ember", featured: true,
  outcomesEn: ["Apply the CIA triad and threat modeling", "Explain identity, authentication and least privilege", "Recognise phishing and social engineering", "Run a basic incident-response process"],
  outcomesAr: ["تطبيق ثالوث CIA ونمذجة التهديدات", "شرح الهوية والمصادقة وأقل الامتيازات", "التعرّف على التصيّد والهندسة الاجتماعية", "تنفيذ عملية استجابة أساسية للحوادث"],
  skills: ["cybersecurity-fundamentals", "threat-modeling", "identity-access", "incident-response", "security-awareness"], rating: 4.6, ratingCount: 980, enrollmentCount: 3900,
  modules: [
    { titleEn: "Thinking like a defender", titleAr: "التفكير كمدافع", lessons: [
      { slug: "cia-triad", titleEn: "The CIA triad", titleAr: "ثالوث CIA", minutes: 11, skills: ["cybersecurity-fundamentals"], freePreview: true, blocks: [
        text(`## Three properties to protect\n\n- **Confidentiality** — only authorised people see the data (encryption, access control).\n- **Integrity** — data is not altered without authorisation (hashes, signatures, audit logs).\n- **Availability** — systems work when needed (redundancy, backups, DDoS protection).\n\nEvery control protects one or more of these; every attack breaks one or more. Ransomware attacks availability (and often confidentiality via leaks). A tampered invoice attacks integrity.\n\n## Risk = likelihood × impact\n\nYou cannot protect everything equally. Rank assets by what breaks if they are lost, then spend on the top of the list. A citizen database and the cafeteria menu do not deserve the same controls.`,
          `## ثلاث خصائص للحماية\n\n- **السرية** — لا يرى البيانات إلا المخوّلون (التشفير، التحكم بالوصول).\n- **السلامة** — لا تُعدَّل البيانات دون تخويل (التجزئة، التوقيعات، سجلات التدقيق).\n- **التوافر** — تعمل الأنظمة عند الحاجة (التكرار، النسخ الاحتياطي، الحماية من حجب الخدمة).\n\nكل ضابط يحمي واحدة أو أكثر منها؛ وكل هجوم يكسر واحدة أو أكثر. برامج الفدية تهاجم التوافر (وغالباً السرية عبر التسريب). الفاتورة المعدَّلة تهاجم السلامة.\n\n## المخاطر = الاحتمال × الأثر\n\nلا يمكنك حماية كل شيء بالتساوي. رتّب الأصول حسب ما ينكسر إن فُقدت ثم أنفق على رأس القائمة. قاعدة بيانات المتعاملين وقائمة طعام الكافتيريا لا تستحقان الضوابط نفسها.`),
        check("A tampered payment amount in a database violates:", "مبلغ دفع معدَّل في قاعدة بيانات ينتهك:", [["Confidentiality", "السرية", false], ["Integrity", "السلامة", true, "Unauthorised alteration is an integrity failure.", "التعديل غير المخوّل فشل في السلامة."], ["Availability", "التوافر", false]]),
      ] },
      { slug: "threat-modeling-basics", titleEn: "Threat modeling basics", titleAr: "أساسيات نمذجة التهديدات", minutes: 14, skills: ["threat-modeling"], blocks: [
        text(`## Four questions\n\n1. **What are we building?** Draw the system: components, data flows, trust boundaries (where data crosses from less trusted to more trusted).\n2. **What can go wrong?** Walk each boundary with STRIDE: Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege.\n3. **What will we do about it?** A control, an acceptance, or a redesign — per threat.\n4. **Did we do a good job?** Review after each significant change.\n\n## Example\n\nA mobile app sends a service request to an API. Boundary: phone → internet → API. Spoofing: can someone submit as another user? (Control: authenticated tokens.) Tampering: can the request be altered in transit? (Control: TLS.) Information disclosure: are IDs guessable? (Control: random IDs + authorisation checks.)`,
          `## أربعة أسئلة\n\n1. **ماذا نبني؟** ارسم النظام: المكونات، تدفقات البيانات، حدود الثقة (حيث تعبر البيانات من الأقل ثقة إلى الأكثر).\n2. **ما الذي قد يسوء؟** امشِ على كل حد بـ STRIDE: الانتحال، العبث، الإنكار، إفشاء المعلومات، حجب الخدمة، رفع الامتيازات.\n3. **ماذا سنفعل؟** ضابط، أو قبول، أو إعادة تصميم — لكل تهديد.\n4. **هل أحسنّا؟** راجع بعد كل تغيير مهم.\n\n## مثال\n\nتطبيق جوّال يرسل طلب خدمة إلى واجهة برمجية. الحد: الهاتف ← الإنترنت ← الواجهة. الانتحال: هل يمكن لأحد الإرسال باسم مستخدم آخر؟ (الضابط: رموز مصادقة.) العبث: هل يمكن تعديل الطلب أثناء النقل؟ (الضابط: TLS.) إفشاء المعلومات: هل المعرّفات قابلة للتخمين؟ (الضابط: معرّفات عشوائية + فحوص تخويل.)`),
        activity("Draw a data-flow diagram of one system you use at work (three boxes are enough). Mark the trust boundaries and list one STRIDE threat per boundary.", "ارسم مخطط تدفق بيانات لنظام تستخدمه في العمل (ثلاثة صناديق تكفي). علّم حدود الثقة واذكر تهديداً واحداً من STRIDE لكل حد.", 15),
      ] },
      { slug: "identity-and-access", titleEn: "Identity, MFA and least privilege", titleAr: "الهوية والمصادقة المتعددة وأقل الامتيازات", minutes: 13, skills: ["identity-access"], blocks: [
        text(`## Identity is the new perimeter\n\nMost breaches begin with a credential. Three defences do most of the work:\n\n- **Multi-factor authentication** everywhere, phishing-resistant (passkeys, hardware keys) for administrators.\n- **Least privilege**: people and services get only the access their role needs, granted for as long as needed, and reviewed quarterly.\n- **Role-based access control**: permissions attached to roles, roles to people — never ad-hoc grants that nobody remembers.\n\n## Joiner · Mover · Leaver\n\nAutomate the lifecycle. The most dangerous account is the one belonging to someone who left six months ago.`,
          `## الهوية هي المحيط الجديد\n\nتبدأ معظم الاختراقات ببيانات اعتماد. ثلاثة دفاعات تقوم بمعظم العمل:\n\n- **المصادقة متعددة العوامل** في كل مكان، ومقاومة للتصيّد (مفاتيح المرور، المفاتيح المادية) للمسؤولين.\n- **أقل الامتيازات**: يحصل الأشخاص والخدمات على الوصول الذي يحتاجه دورهم فقط، للمدة اللازمة، ويُراجع فصلياً.\n- **التحكم بالوصول المبني على الأدوار**: الصلاحيات مرتبطة بالأدوار، والأدوار بالأشخاص — لا منح عشوائية لا يتذكرها أحد.\n\n## الانضمام · الانتقال · المغادرة\n\nأتمت دورة الحياة. أخطر حساب هو حساب شخص غادر قبل ستة أشهر.`),
        check("Which control most reduces the impact of a stolen password?", "أي ضابط يقلل أثر كلمة مرور مسروقة أكثر؟", [["Longer passwords", "كلمات مرور أطول", false], ["Multi-factor authentication", "المصادقة متعددة العوامل", true, "A second factor blocks credential-only access.", "العامل الثاني يمنع الوصول ببيانات الاعتماد وحدها."], ["Password hints", "تلميحات كلمة المرور", false]]),
      ] },
    ] },
    { titleEn: "When things go wrong", titleAr: "حين تسوء الأمور", lessons: [
      { slug: "phishing-and-social-engineering", titleEn: "Phishing and social engineering", titleAr: "التصيّد والهندسة الاجتماعية", minutes: 11, skills: ["security-awareness"], blocks: [
        text(`## Attacks on people\n\nAttackers do not break in; they log in — after persuading someone. Red flags: urgency ("pay within one hour"), authority ("the Director General asked"), unusual channel (WhatsApp for a payment), and requests to bypass process.\n\n## Verify out of band\n\nCall the person on a known number. Never use contact details from the suspicious message itself. Report, don't delete — the security team needs the sample.\n\n## Deepfakes\n\nVoice and video can now be cloned from seconds of public audio. Treat a call requesting money or credentials as unverified until confirmed through a second, independent channel — even if it sounds exactly like your manager.`,
          `## هجمات على البشر\n\nلا يقتحم المهاجمون؛ بل يسجّلون الدخول — بعد إقناع أحدهم. علامات التحذير: الإلحاح («ادفع خلال ساعة»)، السلطة («المدير العام طلب»)، القناة غير المعتادة (واتساب لدفعة)، وطلبات تجاوز الإجراءات.\n\n## تحقق عبر قناة أخرى\n\nاتصل بالشخص على رقم معروف. لا تستخدم بيانات الاتصال من الرسالة المشبوهة نفسها. بلّغ ولا تحذف — يحتاج فريق الأمن العيّنة.\n\n## التزييف العميق\n\nيمكن الآن استنساخ الصوت والفيديو من ثوانٍ من الصوت العام. عامل أي مكالمة تطلب مالاً أو بيانات اعتماد كغير مؤكدة حتى تتأكد عبر قناة ثانية مستقلة — حتى لو بدت تماماً كصوت مديرك.`),
      ] },
      { slug: "incident-response-basics", titleEn: "Incident response basics", titleAr: "أساسيات الاستجابة للحوادث", minutes: 14, skills: ["incident-response"], blocks: [
        text(`## The six phases\n\n1. **Preparation** — plans, contacts, backups tested, logging on.\n2. **Detection & analysis** — is it an incident? What is the scope?\n3. **Containment** — isolate affected systems; preserve evidence.\n4. **Eradication** — remove the attacker's access and tooling.\n5. **Recovery** — restore from clean backups; monitor closely.\n6. **Lessons learned** — blameless review within two weeks.\n\n## Communication\n\nDecide in advance who tells whom: internal leadership, affected customers, regulators (in the UAE, sector regulators and the Cybersecurity Council have notification expectations). Draft templates before you need them.\n\n## Tabletop exercise\n\nOnce a quarter, walk a realistic scenario ("ransomware on the payroll server on Thursday afternoon") with the actual people who would respond. It is the cheapest security investment you will make.`,
          `## المراحل الست\n\n1. **الاستعداد** — الخطط، جهات الاتصال، النسخ الاحتياطية المختبرة، التسجيل مفعّل.\n2. **الاكتشاف والتحليل** — هل هي حادثة؟ ما نطاقها؟\n3. **الاحتواء** — عزل الأنظمة المتأثرة؛ حفظ الأدلة.\n4. **الاستئصال** — إزالة وصول المهاجم وأدواته.\n5. **التعافي** — الاستعادة من نسخ نظيفة؛ المراقبة عن كثب.\n6. **الدروس المستفادة** — مراجعة بلا لوم خلال أسبوعين.\n\n## التواصل\n\nقرر مسبقاً من يخبر من: القيادة الداخلية، المتعاملون المتأثرون، الجهات التنظيمية (في الإمارات، للجهات القطاعية ومجلس الأمن السيبراني توقعات إبلاغ). جهّز القوالب قبل أن تحتاجها.\n\n## التمرين النظري\n\nمرة كل ربع سنة، امشِ عبر سيناريو واقعي («برنامج فدية على خادم الرواتب عصر الخميس») مع الأشخاص الذين سيستجيبون فعلاً. إنه أرخص استثمار أمني ستقوم به.`),
        check("During containment you should:", "أثناء الاحتواء عليك أن:", [["Wipe the affected machine immediately", "تمسح الجهاز المتأثر فوراً", false], ["Isolate it and preserve evidence", "تعزله وتحفظ الأدلة", true, "Evidence is needed for analysis and reporting.", "الأدلة مطلوبة للتحليل والإبلاغ."], ["Ignore it until Monday", "تتجاهله حتى الاثنين", false]]),
      ] },
    ] },
  ],
  assessments: [
    { titleEn: "Cybersecurity Foundations — final assessment", titleAr: "أساسيات الأمن السيبراني — الاختبار النهائي", kind: "FINAL", timeLimitMinutes: 20, passingScore: 70, questions: [
      mc("Ransomware primarily attacks:", "برامج الفدية تهاجم أساساً:", [["Confidentiality only", "السرية فقط"], ["Availability (and often confidentiality)", "التوافر (وغالباً السرية)"], ["Integrity only", "السلامة فقط"], ["None of the triad", "لا شيء من الثالوث"]], 1, "Encrypted systems are unavailable; leaks add disclosure.", "الأنظمة المشفّرة غير متاحة؛ والتسريب يضيف الإفشاء.", { skill: "cybersecurity-fundamentals", difficulty: 2 }),
      sa("In STRIDE, what does the E stand for?", "في STRIDE، إلامَ يرمز حرف E؟", ["elevation of privilege", "elevation", "رفع الامتيازات"], "Elevation of privilege.", "رفع الامتيازات.", { skill: "threat-modeling", difficulty: 2 }),
      tf("Contact details inside a suspicious email are safe to use for verification.", "بيانات الاتصال داخل رسالة مشبوهة آمنة للاستخدام في التحقق.", false, "Verify out of band with known contacts.", "تحقق عبر قناة أخرى بجهات اتصال معروفة.", { skill: "security-awareness", difficulty: 1 }),
      mc("The most dangerous account is usually:", "أخطر حساب عادةً هو:", [["A new joiner's", "حساب موظف جديد"], ["A leaver's account that was never disabled", "حساب مغادر لم يُعطَّل"], ["The CEO's", "حساب الرئيس التنفيذي"], ["A service desk account", "حساب مكتب الخدمة"]], 1, "Orphaned accounts are unmonitored.", "الحسابات اليتيمة غير مراقبة.", { skill: "identity-access", difficulty: 2 }),
      mc("Which incident phase removes the attacker's tooling?", "أي مرحلة من الحادثة تزيل أدوات المهاجم؟", [["Detection", "الاكتشاف"], ["Containment", "الاحتواء"], ["Eradication", "الاستئصال"], ["Preparation", "الاستعداد"]], 2, "Eradication follows containment.", "الاستئصال يلي الاحتواء.", { skill: "incident-response", difficulty: 2 }),
    ] },
  ],
  projects: [{
    slug: "threat-model-report",
    titleEn: "Threat model for a real system", titleAr: "نموذج تهديدات لنظام حقيقي",
    briefEn: "Produce a threat model (diagram, STRIDE table, prioritised controls) for a system you know — an internal app, a public service, or a home network.",
    briefAr: "أنتج نموذج تهديدات (مخطط، جدول STRIDE، ضوابط مرتبة بالأولوية) لنظام تعرفه — تطبيق داخلي، خدمة عامة، أو شبكة منزلية.",
    objectivesEn: ["Draw data flows and trust boundaries", "Enumerate threats systematically", "Prioritise controls by risk"],
    objectivesAr: ["رسم تدفقات البيانات وحدود الثقة", "حصر التهديدات بشكل منهجي", "ترتيب الضوابط حسب المخاطر"],
    instructionsEn: "Submit a document link containing the diagram, a STRIDE table with at least eight threats, and a top-five controls list with justification.",
    instructionsAr: "سلّم رابط مستند يحوي المخطط، وجدول STRIDE بثمانية تهديدات على الأقل، وقائمة بأهم خمسة ضوابط مع التبرير.",
    deliverablesEn: ["Data-flow diagram", "STRIDE table (≥8 threats)", "Top-5 controls with justification"],
    deliverablesAr: ["مخطط تدفق البيانات", "جدول STRIDE (≥8 تهديدات)", "أهم 5 ضوابط مع التبرير"],
    hours: 6,
    rubric: [
      { id: "diagram", titleEn: "Diagram & boundaries", titleAr: "المخطط والحدود", descriptionEn: "Components, flows and trust boundaries are correct.", descriptionAr: "المكونات والتدفقات وحدود الثقة صحيحة.", weight: 30 },
      { id: "threats", titleEn: "Threat coverage", titleAr: "تغطية التهديدات", descriptionEn: "STRIDE applied to each boundary; threats are realistic.", descriptionAr: "STRIDE مطبَّق على كل حد؛ التهديدات واقعية.", weight: 40 },
      { id: "controls", titleEn: "Prioritised controls", titleAr: "الضوابط المرتبة", descriptionEn: "Controls address the highest risks with clear reasoning.", descriptionAr: "الضوابط تعالج أعلى المخاطر بمنطق واضح.", weight: 30 },
    ],
  }],
};

export const digitalTransformation: SeedCourse = {
  slug: "digital-transformation-leadership",
  titleEn: "Digital Transformation Leadership", titleAr: "قيادة التحول الرقمي",
  summaryEn: "Lead change that sticks: strategy, service design, operating models and the human side of transformation.",
  summaryAr: "قُد تغييراً يدوم: الاستراتيجية وتصميم الخدمات ونماذج التشغيل والجانب الإنساني للتحول.",
  descriptionEn: "For managers who own outcomes, not just projects. You will diagnose a transformation, design a citizen- or customer-centred service, build a change plan and measure what matters.",
  descriptionAr: "للمديرين الذين يملكون النتائج لا المشاريع فقط. ستشخّص تحولاً، وتصمّم خدمة تتمحور حول المتعامل، وتبني خطة تغيير، وتقيس ما يهم.",
  category: "digital-transformation", instructor: "amal.alkaabi@nokhba.demo", difficulty: "INTERMEDIATE", hours: 10, cover: "cover-aurora",
  outcomesEn: ["Diagnose where a transformation is stuck", "Apply service-design methods", "Build a change-management plan", "Define outcome metrics and a benefits case"],
  outcomesAr: ["تشخيص أين يتعثر التحول", "تطبيق أساليب تصميم الخدمات", "بناء خطة إدارة التغيير", "تحديد مقاييس النتائج وحالة المنافع"],
  skills: ["digital-transformation", "change-management", "service-design", "strategic-thinking", "leadership"], rating: 4.6, ratingCount: 720, enrollmentCount: 2600,
  modules: [
    { titleEn: "Diagnosis and direction", titleAr: "التشخيص والاتجاه", lessons: [
      { slug: "why-transformations-stall", titleEn: "Why transformations stall", titleAr: "لماذا تتعثر التحولات", minutes: 13, skills: ["digital-transformation", "strategic-thinking"], freePreview: true, blocks: [
        text(`## The usual suspects\n\nStudies of large programmes agree on the causes: technology chosen before the problem, no owner for the outcome, processes digitised as-is (paper forms turned into PDF forms), and incentives that reward activity over results.\n\n## A quick diagnostic\n\nScore your programme 1-5 on each:\n\n1. Is there one accountable executive for the *outcome*?\n2. Is the target expressed as a customer/citizen result, not a system go-live?\n3. Have front-line staff redesigned the process before it was built?\n4. Is data owned, clean and shared across units?\n5. Are budgets released per demonstrated value, not per year?\n\nBelow 15: fix the fundamentals before buying anything.\n\n## The UAE context\n\nNational agendas (We the UAE 2031, Zero Government Bureaucracy) set explicit targets — fewer procedures, faster services, higher satisfaction. Anchor your programme to one of these public commitments; it makes priorities and trade-offs easier to defend.`,
          `## المشتبه بهم المعتادون\n\nتتفق دراسات البرامج الكبيرة على الأسباب: تقنية تُختار قبل المشكلة، ولا مالك للنتيجة، وعمليات تُرقمن كما هي (نماذج ورقية تتحول إلى نماذج PDF)، وحوافز تكافئ النشاط لا النتائج.\n\n## تشخيص سريع\n\nقيّم برنامجك 1-5 على كل بند:\n\n1. هل يوجد مسؤول تنفيذي واحد عن *النتيجة*؟\n2. هل الهدف معبَّر عنه كنتيجة للمتعامل لا كإطلاق نظام؟\n3. هل أعاد موظفو الخط الأمامي تصميم العملية قبل بنائها؟\n4. هل البيانات مملوكة ونظيفة ومشتركة بين الوحدات؟\n5. هل تُصرف الميزانيات حسب القيمة المثبتة لا حسب السنة؟\n\nأقل من 15: أصلح الأساسيات قبل شراء أي شيء.\n\n## السياق الإماراتي\n\nتضع الأجندات الوطنية (نحن الإمارات 2031، تصفير البيروقراطية الحكومية) أهدافاً صريحة — إجراءات أقل، وخدمات أسرع، ورضا أعلى. اربط برنامجك بأحد هذه الالتزامات العامة؛ يجعل الأولويات والمفاضلات أسهل في الدفاع عنها.`),
        check("Turning a paper form into a PDF form is an example of:", "تحويل نموذج ورقي إلى نموذج PDF مثال على:", [["Service redesign", "إعادة تصميم الخدمة", false], ["Digitising the process as-is", "رقمنة العملية كما هي", true, "Nothing about the process improved.", "لم يتحسن شيء في العملية."], ["Change management", "إدارة التغيير", false]]),
      ] },
      { slug: "service-design-in-practice", titleEn: "Service design in practice", titleAr: "تصميم الخدمات عملياً", minutes: 15, skills: ["service-design"], blocks: [
        text(`## Start from the journey\n\nMap the end-to-end journey of one customer through one service — every step, channel, wait and hand-off. Most delay lives in hand-offs between units, not in the units themselves.\n\n## Methods you can run next week\n\n- **Five user interviews** with the people who use the service. Ask what they were trying to achieve and where they got stuck.\n- **Journey map** on one wall: steps on the x-axis, emotion on the y-axis.\n- **Prototype** the new journey with paper or a clickable mock-up; test with five more users before writing a requirement.\n\n## Measure the journey, not the system\n\nTime to outcome, number of visits, re-work rate, satisfaction at the end. System uptime is necessary but says nothing about whether anyone was served.`,
          `## ابدأ من الرحلة\n\nارسم الرحلة الكاملة لمتعامل واحد عبر خدمة واحدة — كل خطوة وقناة وانتظار وتسليم. يعيش معظم التأخير في التسليم بين الوحدات لا داخلها.\n\n## أساليب يمكنك تنفيذها الأسبوع القادم\n\n- **خمس مقابلات** مع من يستخدمون الخدمة. اسأل ما الذي كانوا يحاولون تحقيقه وأين تعثروا.\n- **خريطة رحلة** على جدار واحد: الخطوات على المحور الأفقي، والمشاعر على العمودي.\n- **نموذج أولي** للرحلة الجديدة بالورق أو نموذج قابل للنقر؛ اختبره مع خمسة مستخدمين آخرين قبل كتابة أي متطلب.\n\n## قِس الرحلة لا النظام\n\nالزمن حتى النتيجة، عدد الزيارات، معدل إعادة العمل، الرضا في النهاية. وقت تشغيل النظام ضروري لكنه لا يقول شيئاً عمّا إذا كان أحد قد خُدم.`),
        activity("Map one service you used recently (e.g. renewing a licence) in 6-10 steps. Mark the hand-offs and the single longest wait.", "ارسم خدمة استخدمتها مؤخراً (مثل تجديد رخصة) في 6-10 خطوات. علّم التسليمات وأطول انتظار واحد.", 15),
      ] },
      { slug: "leading-change", titleEn: "Leading the change", titleAr: "قيادة التغيير", minutes: 14, skills: ["change-management", "leadership", "communication"], blocks: [
        text(`## People adopt what they helped shape\n\nA change plan has four parts:\n\n1. **Case for change** — a story leaders can tell in two minutes, with one number.\n2. **Coalition** — the front-line champions and the sceptics you deliberately recruit.\n3. **Capability** — training tied to the moment of need, not a course six months early.\n4. **Consequences** — what changes in targets, recognition and reporting so the new way is the easy way.\n\n## Resistance is information\n\nWhen a team resists, ask what they are protecting: a metric, a relationship, a fear about competence. Address that, not the resistance.\n\n## Cadence\n\nShip something visible every 6-8 weeks. Momentum is the only antidote to transformation fatigue.`,
          `## يتبنّى الناس ما ساعدوا في تشكيله\n\nخطة التغيير من أربعة أجزاء:\n\n1. **مبررات التغيير** — قصة يستطيع القادة روايتها في دقيقتين، مع رقم واحد.\n2. **التحالف** — أبطال الخط الأمامي والمتشككون الذين تجنّدهم عمداً.\n3. **القدرة** — تدريب مرتبط بلحظة الحاجة لا دورة قبل ستة أشهر.\n4. **العواقب** — ما يتغيّر في الأهداف والتقدير والتقارير بحيث تكون الطريقة الجديدة هي الأسهل.\n\n## المقاومة معلومة\n\nحين يقاوم فريق اسأل ما الذي يحميه: مقياس، علاقة، خوف بشأن الكفاءة. عالج ذلك لا المقاومة.\n\n## الإيقاع\n\nأطلق شيئاً مرئياً كل 6-8 أسابيع. الزخم هو الترياق الوحيد لإرهاق التحول.`),
      ] },
    ] },
  ],
  assessments: [
    { titleEn: "Digital Transformation — quiz", titleAr: "التحول الرقمي — اختبار", kind: "QUIZ", passingScore: 70, questions: [
      mc("Most delay in a service journey usually lives in:", "يعيش معظم التأخير في رحلة الخدمة عادةً في:", [["The IT system", "نظام تقنية المعلومات"], ["Hand-offs between units", "التسليم بين الوحدات"], ["The customer", "المتعامل"], ["The budget", "الميزانية"]], 1, "Hand-offs create queues and re-work.", "التسليمات تخلق طوابير وإعادة عمل.", { skill: "service-design", difficulty: 2 }),
      tf("Training should happen as close to the moment of need as possible.", "يجب أن يكون التدريب أقرب ما يمكن إلى لحظة الحاجة.", true, "Capability tied to use sticks.", "القدرة المرتبطة بالاستخدام تدوم.", { skill: "change-management", difficulty: 1 }),
      sa("What should you ask when a team resists a change?", "ما الذي تسأله حين يقاوم فريق تغييراً؟", ["what they are protecting", "what are they protecting", "ما الذي يحمونه", "ماذا يحمون"], "What they are protecting.", "ما الذي يحمونه.", { skill: "leadership", difficulty: 3 }),
    ] },
  ],
};

export const cloudFundamentals: SeedCourse = {
  slug: "cloud-fundamentals",
  titleEn: "Cloud Fundamentals", titleAr: "أساسيات الحوسبة السحابية",
  summaryEn: "Compute, storage, networking and cost in the cloud — including data residency and sovereign-cloud choices.",
  summaryAr: "الحوسبة والتخزين والشبكات والتكلفة في السحابة — بما في ذلك إقامة البيانات وخيارات السحابة السيادية.",
  descriptionEn: "Understand the building blocks every cloud provider offers, how to choose between them, and how to keep bills and risks under control. Includes UAE data-residency considerations.",
  descriptionAr: "افهم اللبنات الأساسية التي يقدّمها كل مزوّد سحابي، وكيف تختار بينها، وكيف تبقي الفواتير والمخاطر تحت السيطرة. يشمل اعتبارات إقامة البيانات في الإمارات.",
  category: "cloud", instructor: "layla.hassan@nokhba.demo", difficulty: "BEGINNER", hours: 8, cover: "cover-ocean",
  outcomesEn: ["Explain IaaS, PaaS and SaaS", "Choose compute and storage options", "Apply the shared-responsibility model", "Estimate and control cloud cost"],
  outcomesAr: ["شرح IaaS وPaaS وSaaS", "اختيار خيارات الحوسبة والتخزين", "تطبيق نموذج المسؤولية المشتركة", "تقدير كلفة السحابة والتحكم بها"],
  skills: ["cloud-fundamentals", "devops", "network-security"], rating: 4.5, ratingCount: 390, enrollmentCount: 1500,
  modules: [
    { titleEn: "Building blocks", titleAr: "اللبنات الأساسية", lessons: [
      { slug: "service-models", titleEn: "IaaS, PaaS, SaaS and shared responsibility", titleAr: "IaaS وPaaS وSaaS والمسؤولية المشتركة", minutes: 12, skills: ["cloud-fundamentals"], freePreview: true, blocks: [
        text(`## Who manages what\n\n- **IaaS** — you rent virtual machines, storage and networks; you manage the OS and above.\n- **PaaS** — the provider runs the platform (database, container runtime); you bring code and data.\n- **SaaS** — you use finished software (email, CRM); you manage users and data.\n\n## Shared responsibility\n\nThe provider secures the cloud *itself* (data centres, hardware, hypervisor). You secure what you put *in* it: identities, configuration, data, patches at your layer. Most cloud breaches are customer misconfigurations — a public storage bucket, an over-privileged key.\n\n## Data residency\n\nRegulated UAE workloads often require data to stay in-country. All major providers now run UAE regions; sovereign-cloud offerings add operational and legal isolation. Decide residency requirements *before* architecture, not after.`,
          `## من يدير ماذا\n\n- **IaaS** — تستأجر آلات افتراضية وتخزيناً وشبكات؛ وتدير نظام التشغيل وما فوقه.\n- **PaaS** — يشغّل المزوّد المنصة (قاعدة بيانات، بيئة حاويات)؛ وتأتي أنت بالكود والبيانات.\n- **SaaS** — تستخدم برمجيات جاهزة (بريد، CRM)؛ وتدير المستخدمين والبيانات.\n\n## المسؤولية المشتركة\n\nيؤمّن المزوّد السحابة *نفسها* (مراكز البيانات، العتاد، المشرف الافتراضي). وتؤمّن أنت ما تضعه *فيها*: الهويات، الإعدادات، البيانات، التحديثات في طبقتك. معظم اختراقات السحابة أخطاء إعداد من العميل — حاوية تخزين عامة، مفتاح بامتيازات زائدة.\n\n## إقامة البيانات\n\nكثيراً ما تتطلب أحمال العمل المنظَّمة في الإمارات بقاء البيانات داخل الدولة. تشغّل كل المزوّدين الكبار الآن مناطق في الإمارات؛ وتضيف عروض السحابة السيادية عزلاً تشغيلياً وقانونياً. قرر متطلبات الإقامة *قبل* المعمارية لا بعدها.`),
        check("A public storage bucket leaking files is the responsibility of:", "حاوية تخزين عامة تسرّب الملفات مسؤولية:", [["The cloud provider", "مزوّد السحابة", false], ["The customer (configuration)", "العميل (الإعدادات)", true, "Configuration is on the customer's side of the line.", "الإعدادات على جانب العميل من الخط."], ["Nobody", "لا أحد", false]]),
      ] },
      { slug: "cost-control", titleEn: "Controlling cloud cost", titleAr: "التحكم بكلفة السحابة", minutes: 12, skills: ["cloud-fundamentals", "devops"], blocks: [
        text(`## Why bills surprise people\n\nCloud is pay-per-use: idle servers, forgotten test environments, unbounded logs and egress traffic all keep billing. Elasticity cuts cost only if you actually scale down.\n\n## Five habits\n\n1. Tag every resource with owner and project; untagged = deleted after 30 days.\n2. Budgets with alerts at 50/80/100%.\n3. Right-size monthly from utilisation data.\n4. Turn off non-production outside working hours.\n5. Commit (reserved/savings plans) only for steady baseline load.\n\n## FinOps\n\nCost is an engineering metric. Show teams their spend weekly, next to their performance metrics, and the behaviour changes on its own.`,
          `## لماذا تفاجئ الفواتير الناس\n\nالسحابة دفع حسب الاستخدام: الخوادم الخاملة، وبيئات الاختبار المنسية، والسجلات غير المحدودة، وحركة الخروج كلها تستمر في الفوترة. المرونة تقلل الكلفة فقط إذا قلّصت فعلاً.\n\n## خمس عادات\n\n1. ضع وسماً لكل مورد بالمالك والمشروع؛ بلا وسم = يُحذف بعد 30 يوماً.\n2. ميزانيات بتنبيهات عند 50/80/100%.\n3. ضبط الأحجام شهرياً من بيانات الاستخدام.\n4. أطفئ بيئات غير الإنتاج خارج ساعات العمل.\n5. التزم (خطط محجوزة/توفير) للحمل الأساسي الثابت فقط.\n\n## FinOps\n\nالكلفة مقياس هندسي. أظهر للفرق إنفاقها أسبوعياً بجانب مقاييس أدائها ويتغير السلوك من تلقاء نفسه.`),
      ] },
    ] },
  ],
  assessments: [
    { titleEn: "Cloud Fundamentals — quiz", titleAr: "أساسيات السحابة — اختبار", kind: "QUIZ", passingScore: 70, questions: [
      mc("A managed database you connect your code to is:", "قاعدة بيانات مُدارة تربط بها كودك هي:", [["IaaS", "IaaS"], ["PaaS", "PaaS"], ["SaaS", "SaaS"], ["On-premises", "محلية"]], 1, "The provider runs the platform.", "المزوّد يشغّل المنصة.", { skill: "cloud-fundamentals", difficulty: 1 }),
      tf("Reserved capacity is a good fit for spiky, unpredictable load.", "السعة المحجوزة مناسبة للحمل المتقلب غير المتوقع.", false, "Commit only for steady baseline.", "التزم للحمل الأساسي الثابت فقط.", { skill: "cloud-fundamentals", difficulty: 2 }),
      sa("What practice treats cloud cost as an engineering metric shared with teams?", "ما الممارسة التي تعامل كلفة السحابة كمقياس هندسي مشترك مع الفرق؟", ["finops", "FinOps"], "FinOps.", "FinOps.", { skill: "devops", difficulty: 2 }),
    ] },
  ],
};
